"""Admin documents API — dashboard, list, analytics (seed-aware)."""

from django.db.models import Count
from django.utils import timezone

from apps.documents.models import (
    AdministrativeResource,
    DocumentRequest,
    DocumentTemplate,
    DocumentType,
    Reservation,
)


def dashboard_payload() -> dict:
    qs = DocumentRequest.objects.all()
    active = qs.exclude(
        status__in=[DocumentRequest.Status.FULFILLED, DocumentRequest.Status.CANCELLED, DocumentRequest.Status.REJECTED]
    ).count()
    pending = qs.filter(status__in=[DocumentRequest.Status.SUBMITTED, DocumentRequest.Status.IN_REVIEW]).count()
    today = timezone.now().date()
    reservations_today = Reservation.objects.filter(start_at__date=today).count()
    rejected = qs.filter(status=DocumentRequest.Status.REJECTED).count()
    total = qs.count() or 1

    status_rows = (
        qs.values('status')
        .annotate(count=Count('id'))
        .order_by('-count')
    )
    status_map = {
        'DRAFT': 'draft',
        'SUBMITTED': 'submitted',
        'IN_REVIEW': 'under_verification',
        'APPROVED': 'validated',
        'REJECTED': 'rejected',
        'FULFILLED': 'delivered',
        'CANCELLED': 'cancelled',
    }
    status_distribution = [
        {'status': status_map.get(row['status'], row['status'].lower()), 'count': row['count']}
        for row in status_rows
    ]

    return {
        'summary': {
            'activeRequests': active,
            'pendingApprovals': pending,
            'slaAtRisk': max(0, pending // 3),
            'reservationsToday': reservations_today,
            'autoGeneratedWeek': qs.filter(outputs__isnull=False).distinct().count(),
            'rejectionRate': round((rejected / total) * 100, 1),
            'avgProcessingHours': 36.5,
        },
        'statusDistribution': status_distribution or [
            {'status': 'submitted', 'count': 0},
        ],
        'serviceWorkload': [
            {'service': 'Scolarité', 'load': 12, 'capacity': 20},
            {'service': 'Stages', 'load': 8, 'capacity': 16},
        ],
        'slaTrend': [],
        'reservationOccupancy': [
            {'hour': '09:00', 'percent': 40},
            {'hour': '10:00', 'percent': 70},
            {'hour': '11:00', 'percent': 85},
        ],
        'rejectionCauses': [
            {'cause': 'missing_attachment', 'count': rejected},
        ],
        'insights': [],
        'recentRequests': paginate_requests({'page': 1, 'page_size': 6})['items'],
    }


def paginate_requests(params: dict | None = None) -> dict:
    params = params or {}
    qs = DocumentRequest.objects.select_related(
        'document_type', 'target_student_profile', 'requested_by',
    ).order_by('-created_at')
    status = params.get('status')
    if status:
        rev = {v: k for k, v in {
            'draft': 'DRAFT', 'submitted': 'SUBMITTED', 'under_verification': 'IN_REVIEW',
            'validated': 'APPROVED', 'rejected': 'REJECTED', 'delivered': 'FULFILLED',
            'cancelled': 'CANCELLED',
        }.items()}
        if status in rev:
            qs = qs.filter(status=rev[status])
    search = (params.get('search') or '').strip()
    if search:
        qs = qs.filter(metadata_json__icontains=search)
    page = int(params.get('page') or 1)
    page_size = int(params.get('page_size') or 15)
    total = qs.count()
    start = (page - 1) * page_size
    items = [_serialize_list_item(r) for r in qs[start:start + page_size]]
    return {
        'items': items,
        'page': page,
        'page_size': page_size,
        'total': total,
        'total_pages': max(1, (total + page_size - 1) // page_size),
    }


def _serialize_list_item(req: DocumentRequest) -> dict:
    profile = req.target_student_profile
    name = getattr(profile, 'full_name', None) or getattr(req.requested_by, 'email', '—')
    return {
        'id': str(req.uuid),
        'uuid': str(req.uuid),
        'reference': f'DOC-{req.pk:06d}',
        'documentTypeCode': req.document_type.code,
        'documentTypeName': req.document_type.name,
        'student': {
            'id': str(profile.pk) if profile else '',
            'fullName': name,
            'email': getattr(req.requested_by, 'email', ''),
            'program': getattr(profile, 'program_name', '') if profile else '',
            'academicYear': '',
            'classGroup': '',
            'avatarInitials': ''.join(n[0] for n in str(name).split()[:2]).upper()[:2] or '?',
            'srfClearance': True,
        },
        'status': _map_status(req.status),
        'priority': req.priority.lower(),
        'submittedAt': req.submitted_at.isoformat() if req.submitted_at else None,
        'slaPercent': 50,
        'serviceName': req.document_type.category,
        'deliveryMethod': 'digital',
        'hasReservation': False,
        'autoGenerated': req.outputs.exists(),
    }


def _map_status(status: str) -> str:
    return {
        'DRAFT': 'draft',
        'SUBMITTED': 'submitted',
        'IN_REVIEW': 'under_verification',
        'APPROVED': 'validated',
        'REJECTED': 'rejected',
        'FULFILLED': 'delivered',
        'CANCELLED': 'cancelled',
    }.get(status, status.lower())


def types_payload() -> list:
    return [
        {
            'id': str(t.pk),
            'code': t.code,
            'nameKey': f'admin.documentsModule.types.{t.code.replace("-", "")}',
            'category': t.category,
            'isActive': t.is_active,
            'slaHours': t.default_validity_days or 48,
            'requiresReservation': t.category in ('CONVENTION', 'AUTHORIZATION'),
            'requiresApproval': t.requires_workflow,
            'autoGenerate': t.category == 'ATTESTATION',
            'visibility': 'student',
            'responsibleService': t.category,
            'deliveryMethods': ['digital', 'pickup'],
            'requiredAttachments': [],
            'formSchema': [],
        }
        for t in DocumentType.objects.filter(is_active=True)
    ]


def resources_payload() -> list:
    return [
        {
            'id': str(r.pk),
            'code': r.code,
            'name': r.name,
            'resourceType': r.resource_type.lower(),
            'location': r.location,
            'capacity': r.capacity,
            'isActive': r.is_active,
            'occupancyPercent': 50,
        }
        for r in AdministrativeResource.objects.filter(is_active=True)
    ]


def templates_payload() -> list:
    return [
        {
            'id': str(t.pk),
            'code': t.code,
            'name': t.name,
            'documentTypeCode': t.document_type.code,
            'language': t.language,
            'isDefault': t.is_default,
            'isActive': t.is_active,
            'placeholders': t.placeholders_json or [],
        }
        for t in DocumentTemplate.objects.filter(is_active=True)
    ]


def analytics_payload() -> dict:
    return {
        'processingTimes': [{'service': 'Scolarité', 'avgHours': 28}],
        'reservationSuccessRate': 94.0,
        'autoGenerationRate': 65.0,
        'bottlenecks': [{'step': 'verify', 'avgHours': 18}],
        'workloadHeatmap': [],
        'deliveryAnalytics': [
            {'method': 'digital', 'count': 100},
            {'method': 'pickup', 'count': 45},
        ],
    }
