"""Admin documents API — dashboard, list, analytics."""

from __future__ import annotations

from collections import Counter
from datetime import timedelta

from django.db.models import Count, Q
from django.utils import timezone

from apps.documents.models import (
    AdministrativeResource,
    DocumentRequest,
    DocumentTemplate,
    DocumentType,
    DocumentWorkflow,
    Reservation,
)

STATUS_MAP = {
    'DRAFT': 'draft',
    'SUBMITTED': 'submitted',
    'IN_REVIEW': 'under_verification',
    'APPROVED': 'validated',
    'REJECTED': 'rejected',
    'FULFILLED': 'delivered',
    'CANCELLED': 'cancelled',
}

STATUS_REVERSE = {v: k for k, v in STATUS_MAP.items()}

ACTIVE_STATUSES = [
    DocumentRequest.Status.DRAFT,
    DocumentRequest.Status.SUBMITTED,
    DocumentRequest.Status.IN_REVIEW,
    DocumentRequest.Status.APPROVED,
]

PENDING_STATUSES = [DocumentRequest.Status.SUBMITTED, DocumentRequest.Status.IN_REVIEW]

TERMINAL_STATUSES = [
    DocumentRequest.Status.FULFILLED,
    DocumentRequest.Status.CANCELLED,
    DocumentRequest.Status.REJECTED,
]

OCCUPANCY_HOURS = ['09:00', '10:00', '11:00', '12:00', '14:00', '15:00', '16:00', '17:00']

LIST_SELECT_RELATED = (
    'document_type',
    'target_student_profile',
    'target_student_profile__user',
    'target_student_profile__user__profile',
    'target_student_profile__class_group',
    'target_student_profile__filiere',
    'requested_by',
)


def dashboard_payload() -> dict:
    qs = DocumentRequest.objects.all()
    active = qs.exclude(status__in=TERMINAL_STATUSES).count()
    pending = qs.filter(status__in=PENDING_STATUSES).count()
    today = timezone.now().date()
    reservations_today = Reservation.objects.filter(start_at__date=today).count()
    rejected = qs.filter(status=DocumentRequest.Status.REJECTED).count()
    total = qs.count()
    rejection_rate = round((rejected / total) * 100, 1) if total else 0.0

    status_distribution = _status_distribution(qs)

    return {
        'summary': {
            'activeRequests': active,
            'pendingApprovals': pending,
            'slaAtRisk': _sla_at_risk_count(qs),
            'reservationsToday': reservations_today,
            'autoGeneratedWeek': _auto_generated_week_count(),
            'rejectionRate': rejection_rate,
            'avgProcessingHours': _avg_processing_hours(qs),
        },
        'statusDistribution': status_distribution,
        'serviceWorkload': service_workload_payload(),
        'slaTrend': [],
        'reservationOccupancy': reservation_occupancy_payload(today),
        'rejectionCauses': _rejection_causes(qs),
        'insights': _dashboard_insights(qs, pending),
        'recentRequests': paginate_requests({'page': 1, 'page_size': 6})['items'],
    }


def paginate_requests(params: dict | None = None) -> dict:
    params = params or {}
    qs = _filter_requests(params)
    page = max(1, int(params.get('page') or 1))
    page_size = max(1, min(100, int(params.get('page_size') or 15)))
    total = qs.count()
    start = (page - 1) * page_size
    items = [_serialize_list_item(r) for r in qs[start:start + page_size]]
    return {
        'items': items,
        'page': page,
        'page_size': page_size,
        'total': total,
        'total_pages': max(1, (total + page_size - 1) // page_size) if total else 0,
    }


def detail_payload(req: DocumentRequest) -> dict:
    item = _serialize_list_item(req)
    meta = req.metadata_json or {}
    reservation = _reservation_from_metadata(meta)

    item.update({
        'reason': req.reason,
        'fields': [
            {
                'name': f.field_name,
                'labelKey': f.field_label or f.field_name,
                'value': _field_display_value(f.field_value_json),
            }
            for f in req.fields.all()
        ],
        'attachments': [
            {
                'id': str(a.pk),
                'name': a.original_filename or a.file.name.split('/')[-1],
                'type': a.attachment_type.lower(),
                'uploadedAt': a.created_at.isoformat(),
            }
            for a in req.attachments.all()
        ],
        'workflowSteps': _workflow_steps(req),
        'validationHistory': _validation_history(req),
        'generatedOutputs': [
            {
                'id': str(o.pk),
                'format': o.format.lower(),
                'generatedAt': o.generated_at.isoformat(),
                'signed': o.is_signed,
            }
            for o in req.outputs.all()
        ],
        'insights': _detail_insights(req),
        'rejectionReason': req.rejection_reason or None,
        'reservation': reservation,
        'slaDeadline': _sla_deadline(req),
    })
    return item


def perform_request_action(req: DocumentRequest, action: str, user, payload: dict | None = None) -> dict:
    payload = payload or {}
    action = (action or '').strip().lower()

    if action == 'approve':
        if req.status not in PENDING_STATUSES:
            raise ValueError('Request cannot be approved in its current status.')
        req.status = DocumentRequest.Status.APPROVED
        req.reviewed_at = timezone.now()
        req.reviewed_by = user
        req.rejection_reason = ''
        req.save(update_fields=['status', 'reviewed_at', 'reviewed_by', 'rejection_reason', 'updated_at'])
        _log_workflow(req, 'validated', DocumentWorkflow.Decision.APPROVE, user, payload.get('note', ''))
        return detail_payload(req)

    if action == 'reject':
        if req.status not in PENDING_STATUSES + [DocumentRequest.Status.APPROVED]:
            raise ValueError('Request cannot be rejected in its current status.')
        reason = (payload.get('reason') or payload.get('rejectionReason') or '').strip()
        if not reason:
            raise ValueError('A rejection reason is required.')
        req.status = DocumentRequest.Status.REJECTED
        req.reviewed_at = timezone.now()
        req.reviewed_by = user
        req.rejection_reason = reason
        req.save(update_fields=['status', 'reviewed_at', 'reviewed_by', 'rejection_reason', 'updated_at'])
        _log_workflow(req, 'rejected', DocumentWorkflow.Decision.REJECT, user, reason)
        return detail_payload(req)

    if action == 'start_review':
        if req.status != DocumentRequest.Status.SUBMITTED:
            raise ValueError('Only submitted requests can enter review.')
        req.status = DocumentRequest.Status.IN_REVIEW
        req.save(update_fields=['status', 'updated_at'])
        _log_workflow(req, 'under_verification', DocumentWorkflow.Decision.NONE, user)
        return detail_payload(req)

    raise ValueError(f'Unknown action: {action}')


def service_workload_payload() -> list[dict]:
    active_qs = DocumentRequest.objects.exclude(status__in=TERMINAL_STATUSES)
    rows = (
        active_qs.values('document_type__category')
        .annotate(load=Count('id'))
        .order_by('-load')
    )
    capacities = {
        row['category']: row['count']
        for row in DocumentType.objects.filter(is_active=True).values('category').annotate(count=Count('id'))
    }
    workload = []
    for row in rows:
        category = row['document_type__category'] or 'OTHER'
        load = row['load']
        type_count = max(1, capacities.get(category, 1))
        capacity = max(load, type_count * 5)
        workload.append({'service': category, 'load': load, 'capacity': capacity})
    return workload


def reservation_occupancy_payload(day=None) -> list[dict]:
    day = day or timezone.now().date()
    bookable = AdministrativeResource.objects.filter(is_active=True, is_bookable=True).count() or 1
    reservations = Reservation.objects.filter(
        start_at__date=day,
        status__in=[
            Reservation.Status.PENDING,
            Reservation.Status.APPROVED,
            Reservation.Status.CHECKED_IN,
            Reservation.Status.COMPLETED,
        ],
    )
    occupancy = []
    for hour_label in OCCUPANCY_HOURS:
        hour = int(hour_label.split(':')[0])
        count_at_hour = reservations.filter(start_at__hour=hour).count()
        percent = min(100, round((count_at_hour / bookable) * 100))
        occupancy.append({'hour': hour_label, 'percent': percent})
    return occupancy


def reservations_payload(params: dict | None = None) -> dict:
    params = params or {}
    day = params.get('date')
    if day:
        try:
            from datetime import date as date_cls
            target = date_cls.fromisoformat(str(day))
        except ValueError:
            target = timezone.now().date()
    else:
        target = timezone.now().date()

    reservations = (
        Reservation.objects.select_related('resource', 'reserved_by')
        .filter(start_at__date=target)
        .order_by('start_at')
    )
    return {
        'date': target.isoformat(),
        'occupancy': reservation_occupancy_payload(target),
        'total': reservations.count(),
        'items': [
            {
                'id': str(r.uuid),
                'resourceName': r.resource.name,
                'resourceType': r.resource.resource_type.lower(),
                'startAt': r.start_at.isoformat(),
                'endAt': r.end_at.isoformat(),
                'status': r.status.lower(),
                'location': r.resource.location,
                'title': r.title,
            }
            for r in reservations
        ],
    }


def workload_payload() -> dict:
    return {'items': service_workload_payload()}


def _filter_requests(params: dict):
    qs = DocumentRequest.objects.select_related(*LIST_SELECT_RELATED).prefetch_related('outputs')

    status = params.get('status')
    if status and status in STATUS_REVERSE:
        qs = qs.filter(status=STATUS_REVERSE[status])

    priority = (params.get('priority') or '').strip().lower()
    if priority in ('low', 'normal', 'high', 'urgent'):
        qs = qs.filter(priority=priority.upper())

    document_type = (params.get('document_type') or '').strip()
    if document_type:
        qs = qs.filter(document_type__code=document_type)

    service = (params.get('service') or '').strip()
    if service:
        qs = qs.filter(document_type__category=service)

    search = (params.get('search') or '').strip()
    if search:
        qs = _apply_search(qs, search)

    ordering = (params.get('ordering') or '-created_at').strip()
    allowed_ordering = {
        '-created_at': '-created_at',
        'created_at': 'created_at',
        '-submitted_at': '-submitted_at',
        'submitted_at': 'submitted_at',
        '-updated_at': '-updated_at',
        'updated_at': 'updated_at',
    }
    qs = qs.order_by(allowed_ordering.get(ordering, '-created_at'))
    return qs


def _apply_search(qs, search: str):
    if search.upper().startswith('DOC-'):
        try:
            pk = int(search.split('-', 1)[1])
            return qs.filter(pk=pk)
        except (ValueError, IndexError):
            pass
    return qs.filter(
        Q(document_type__code__icontains=search)
        | Q(document_type__name__icontains=search)
        | Q(reason__icontains=search)
        | Q(metadata_json__icontains=search)
        | Q(requested_by__email__icontains=search)
        | Q(target_student_profile__user__email__icontains=search)
        | Q(target_student_profile__program_major__icontains=search)
        | Q(target_student_profile__current_class__icontains=search)
    )


def _serialize_list_item(req: DocumentRequest) -> dict:
    profile = req.target_student_profile
    user = profile.user if profile else req.requested_by
    name = user.full_name if user else '—'
    program = ''
    class_group = ''
    academic_year = ''
    if profile:
        program = profile.program_major or (profile.filiere.name if profile.filiere_id else '')
        class_group = profile.current_class or (
            profile.class_group.name if profile.class_group_id else ''
        )
        if profile.academic_level_id:
            academic_year = profile.academic_level.name

    meta = req.metadata_json or {}
    delivery = meta.get('deliveryMethod') or 'digital'
    has_reservation = bool(meta.get('reservationUuid') or meta.get('hasReservation'))

    return {
        'id': str(req.uuid),
        'uuid': str(req.uuid),
        'reference': f'DOC-{req.pk:06d}',
        'documentTypeCode': req.document_type.code,
        'documentTypeName': req.document_type.name,
        'student': {
            'id': str(profile.pk) if profile else '',
            'fullName': name,
            'email': getattr(user, 'email', ''),
            'program': program,
            'academicYear': academic_year,
            'classGroup': class_group,
            'avatarInitials': ''.join(n[0] for n in str(name).split()[:2]).upper()[:2] or '?',
            'srfClearance': meta.get('srfClearance', True),
        },
        'status': _map_status(req.status),
        'priority': req.priority.lower(),
        'submittedAt': req.submitted_at.isoformat() if req.submitted_at else None,
        'slaPercent': _compute_sla_percent(req),
        'slaDeadline': _sla_deadline(req),
        'serviceName': req.document_type.category,
        'deliveryMethod': delivery,
        'hasReservation': has_reservation,
        'autoGenerated': req.outputs.exists(),
    }


def _map_status(status: str) -> str:
    return STATUS_MAP.get(status, status.lower())


def _sla_hours(document_type: DocumentType) -> float:
    config = document_type.service_config_json or {}
    processing = config.get('processing') or {}
    hours = processing.get('slaHours')
    if hours:
        return float(hours)
    if document_type.default_validity_days:
        return float(document_type.default_validity_days)
    return 48.0


def _compute_sla_percent(req: DocumentRequest) -> int:
    if req.status in TERMINAL_STATUSES:
        return 100 if req.status != DocumentRequest.Status.REJECTED else 0
    if not req.submitted_at:
        return 0
    sla_hours = _sla_hours(req.document_type)
    elapsed_hours = (timezone.now() - req.submitted_at).total_seconds() / 3600
    return min(100, max(0, round((elapsed_hours / sla_hours) * 100)))


def _sla_deadline(req: DocumentRequest) -> str | None:
    if not req.submitted_at:
        return None
    deadline = req.submitted_at + timedelta(hours=_sla_hours(req.document_type))
    return deadline.isoformat()


def _avg_processing_hours(qs) -> float:
    completed = qs.filter(reviewed_at__isnull=False, submitted_at__isnull=False).only(
        'submitted_at', 'reviewed_at'
    )
    hours = [
        (row.reviewed_at - row.submitted_at).total_seconds() / 3600
        for row in completed
        if row.reviewed_at and row.submitted_at
    ]
    return round(sum(hours) / len(hours), 1) if hours else 0.0


def _sla_at_risk_count(qs) -> int:
    now = timezone.now()
    at_risk = 0
    pending = qs.filter(status__in=PENDING_STATUSES).select_related('document_type')
    for req in pending:
        if not req.submitted_at:
            continue
        sla_hours = _sla_hours(req.document_type)
        elapsed = (now - req.submitted_at).total_seconds() / 3600
        if elapsed >= sla_hours * 0.75:
            at_risk += 1
    return at_risk


def _auto_generated_week_count() -> int:
    week_ago = timezone.now() - timedelta(days=7)
    return (
        DocumentRequest.objects.filter(outputs__generated_at__gte=week_ago)
        .distinct()
        .count()
    )


def _status_distribution(qs) -> list[dict]:
    rows = qs.values('status').annotate(count=Count('id')).order_by('-count')
    return [
        {'status': STATUS_MAP.get(row['status'], row['status'].lower()), 'count': row['count']}
        for row in rows
    ]


def _rejection_causes(qs) -> list[dict]:
    rejected = qs.filter(status=DocumentRequest.Status.REJECTED)
    if not rejected.exists():
        return []
    causes: Counter[str] = Counter()
    for req in rejected.only('rejection_reason'):
        reason = (req.rejection_reason or '').lower()
        if not reason:
            causes['other'] += 1
        elif 'attachment' in reason or 'pièce' in reason or 'piece' in reason:
            causes['missing_attachment'] += 1
        elif 'srf' in reason or 'financial' in reason or 'impay' in reason:
            causes['srf_unpaid'] += 1
        elif 'invalid' in reason or 'invalide' in reason:
            causes['invalid_data'] += 1
        else:
            causes['other'] += 1
    return [{'cause': cause, 'count': count} for cause, count in causes.most_common()]


def _dashboard_insights(qs, pending: int) -> list[dict]:
    insights = []
    at_risk = _sla_at_risk_count(qs)
    if at_risk:
        insights.append({
            'id': 'sla-at-risk',
            'severity': 'warning',
            'messageKey': 'admin.documentsModule.insights.slaAtRisk',
        })
    if pending > 10:
        insights.append({
            'id': 'high-pending',
            'severity': 'info',
            'messageKey': 'admin.documentsModule.insights.highPending',
        })
    return insights


def _detail_insights(req: DocumentRequest) -> list[str]:
    insights = []
    meta = req.metadata_json or {}
    if meta.get('srfClearance', True):
        insights.append('admin.documentsModule.insights.srfClear')
    if _compute_sla_percent(req) >= 90 and req.status in PENDING_STATUSES:
        insights.append('admin.documentsModule.insights.slaUrgent')
    return insights


def _workflow_steps(req: DocumentRequest) -> list[dict]:
    steps = list(req.workflow_steps.select_related('performed_by').order_by('created_at'))
    if steps:
        return [
            {
                'id': str(step.pk),
                'code': step.step_code,
                'labelKey': f'admin.documentsModule.workflow.{step.step_code}',
                'status': step.status.lower(),
                'performedAt': step.performed_at.isoformat() if step.performed_at else None,
                'performedBy': step.performed_by.full_name if step.performed_by else None,
                'notes': step.notes,
            }
            for step in steps
        ]
    return _synthetic_workflow(req)


def _synthetic_workflow(req: DocumentRequest) -> list[dict]:
    ordered = ['submitted', 'under_verification', 'validated', 'delivered']
    current = _map_status(req.status)
    current_idx = ordered.index(current) if current in ordered else -1
    if current == 'rejected':
        current_idx = ordered.index('under_verification')
    result = []
    for idx, code in enumerate(ordered):
        if current == 'rejected' and code == 'validated':
            status = 'failed'
        elif idx < current_idx:
            status = 'completed'
        elif idx == current_idx:
            status = 'in_progress' if current not in ('delivered', 'cancelled') else 'completed'
        else:
            status = 'pending'
        result.append({
            'id': f'{req.pk}-{code}',
            'code': code,
            'labelKey': f'admin.documentsModule.workflow.{code}',
            'status': status,
            'performedAt': req.submitted_at.isoformat() if code == 'submitted' and req.submitted_at else None,
            'performedBy': None,
            'notes': req.rejection_reason if current == 'rejected' and code == 'under_verification' else '',
        })
    return result


def _validation_history(req: DocumentRequest) -> list[dict]:
    history = []
    if req.submitted_at:
        history.append({
            'at': req.submitted_at.isoformat(),
            'by': req.requested_by.full_name if req.requested_by_id else '—',
            'action': 'submitted',
        })
    if req.reviewed_at and req.reviewed_by_id:
        history.append({
            'at': req.reviewed_at.isoformat(),
            'by': req.reviewed_by.full_name,
            'action': _map_status(req.status),
            'note': req.rejection_reason or None,
        })
    return history


def _reservation_from_metadata(meta: dict) -> dict | None:
    reservation_uuid = meta.get('reservationUuid')
    if not reservation_uuid:
        return None
    try:
        reservation = Reservation.objects.select_related('resource').get(uuid=reservation_uuid)
    except Reservation.DoesNotExist:
        return None
    return {
        'id': str(reservation.uuid),
        'resourceName': reservation.resource.name,
        'resourceType': reservation.resource.resource_type.lower(),
        'startAt': reservation.start_at.isoformat(),
        'endAt': reservation.end_at.isoformat(),
        'status': reservation.status.lower(),
        'location': reservation.resource.location,
    }


def _field_display_value(value) -> str:
    if value is None:
        return ''
    if isinstance(value, (dict, list)):
        return str(value)
    return str(value)


def _log_workflow(req, step_code: str, decision: str, user, notes: str = '') -> None:
    DocumentWorkflow.objects.create(
        document_request=req,
        step_code=step_code,
        step_label=step_code.replace('_', ' ').title(),
        status=DocumentWorkflow.Status.COMPLETED,
        decision=decision,
        performed_by=user,
        performed_at=timezone.now(),
        notes=notes,
    )


def types_payload() -> list:
    return [
        {
            'id': str(t.pk),
            'code': t.code,
            'nameKey': f'admin.documentsModule.types.{t.code.replace("-", "")}',
            'category': t.category,
            'isActive': t.is_active,
            'slaHours': _sla_hours(t),
            'requiresReservation': t.category in ('CONVENTION', 'AUTHORIZATION'),
            'requiresApproval': t.requires_workflow,
            'autoGenerate': t.category == 'ATTESTATION',
            'visibility': 'student',
            'responsibleService': t.category,
            'deliveryMethods': ['digital', 'pickup'],
            'requiredAttachments': [],
            'formSchema': [],
        }
        for t in DocumentType.objects.filter(is_active=True)
    ]


def resources_payload() -> list:
    today = timezone.now().date()
    bookable = AdministrativeResource.objects.filter(is_active=True, is_bookable=True)
    result = []
    for resource in bookable:
        reservations_today = Reservation.objects.filter(
            resource=resource,
            start_at__date=today,
            status__in=[
                Reservation.Status.PENDING,
                Reservation.Status.APPROVED,
                Reservation.Status.CHECKED_IN,
            ],
        ).count()
        capacity = max(1, resource.capacity or 1)
        occupancy = min(100, round((reservations_today / capacity) * 100))
        result.append({
            'id': str(resource.pk),
            'code': resource.code,
            'name': resource.name,
            'resourceType': resource.resource_type.lower(),
            'location': resource.location,
            'capacity': resource.capacity,
            'isActive': resource.is_active,
            'occupancyPercent': occupancy,
        })
    return result


def templates_payload() -> list:
    return [
        {
            'id': str(t.pk),
            'code': t.code,
            'name': t.name,
            'documentTypeCode': t.document_type.code,
            'language': t.language,
            'isDefault': t.is_default,
            'isActive': t.is_active,
            'placeholders': t.placeholders_json or [],
        }
        for t in DocumentTemplate.objects.filter(is_active=True)
    ]


def analytics_payload() -> dict:
    qs = DocumentRequest.objects.select_related('document_type')
    total = qs.count()
    with_outputs = qs.filter(outputs__isnull=False).distinct().count()
    auto_rate = round((with_outputs / total) * 100, 1) if total else 0.0

    reservations = Reservation.objects.all()
    res_total = reservations.count()
    res_success = reservations.filter(
        status__in=[Reservation.Status.COMPLETED, Reservation.Status.CHECKED_IN, Reservation.Status.APPROVED]
    ).count()
    reservation_success = round((res_success / res_total) * 100, 1) if res_total else 0.0

    processing_times = []
    for row in (
        qs.filter(reviewed_at__isnull=False, submitted_at__isnull=False)
        .values('document_type__category')
        .distinct()
    ):
        category = row['document_type__category']
        subset = qs.filter(
            document_type__category=category,
            reviewed_at__isnull=False,
            submitted_at__isnull=False,
        ).only('submitted_at', 'reviewed_at')
        hours = [
            (r.reviewed_at - r.submitted_at).total_seconds() / 3600
            for r in subset
            if r.reviewed_at and r.submitted_at
        ]
        if hours:
            processing_times.append({
                'service': category,
                'avgHours': round(sum(hours) / len(hours), 1),
            })

    delivery_counts: Counter[str] = Counter()
    for req in qs.only('metadata_json'):
        method = (req.metadata_json or {}).get('deliveryMethod', 'digital')
        delivery_counts[method] += 1

    in_review = qs.filter(status=DocumentRequest.Status.IN_REVIEW, submitted_at__isnull=False)
    review_hours = [
        (timezone.now() - r.submitted_at).total_seconds() / 3600
        for r in in_review
        if r.submitted_at
    ]
    bottlenecks = []
    if review_hours:
        bottlenecks.append({
            'step': 'verify',
            'avgHours': round(sum(review_hours) / len(review_hours), 1),
        })

    return {
        'processingTimes': processing_times,
        'reservationSuccessRate': reservation_success,
        'autoGenerationRate': auto_rate,
        'bottlenecks': bottlenecks,
        'workloadHeatmap': [],
        'deliveryAnalytics': [
            {'method': method, 'count': count}
            for method, count in delivery_counts.most_common()
        ],
    }
