"""Instant document generation for auto-generate catalog services."""

from __future__ import annotations

import hashlib
import os
import uuid

from django.core.files.base import ContentFile
from django.utils import timezone

from core.media_urls import build_absolute_media_url

from apps.documents.models import DocumentOutput, DocumentRequest, DocumentType
from apps.documents.services import catalog as catalog_service
from apps.documents.services.admin_api import PENDING_STATUSES


def auto_generate_enabled(catalog_item: dict) -> bool:
    availability = (catalog_item.get('config') or {}).get('availability') or {}
    return bool(catalog_item.get('autoGenerate') or availability.get('autoGenerateEnabled'))


def _output_format_from_name(file_name: str) -> str:
    ext = file_name.rsplit('.', 1)[-1].lower() if '.' in file_name else 'pdf'
    if ext == 'docx':
        return DocumentOutput.Format.DOCX
    if ext == 'html':
        return DocumentOutput.Format.HTML
    return DocumentOutput.Format.PDF


def _serialize_output(output: DocumentOutput, http_request=None) -> dict:
    file_name = os.path.basename(output.file.name) if output.file else 'document.pdf'
    file_url = None
    if output.file:
        try:
            file_url = build_absolute_media_url(output.file.url, http_request)
        except (ValueError, AttributeError):
            file_url = None
    return {
        'id': str(output.pk),
        'fileName': file_name,
        'fileUrl': file_url,
        'format': output.format.lower(),
        'generatedAt': output.generated_at.isoformat(),
    }


def _build_response(req: DocumentRequest, output: DocumentOutput, http_request=None) -> dict:
    return {
        'reference': f'DOC-{req.pk:06d}',
        'requestId': str(req.uuid),
        'status': 'delivered',
        'output': _serialize_output(output, http_request),
    }


def generate_document(profile, user, pk: int, http_request=None) -> dict:
    catalog_item = catalog_service.catalog_detail(pk)
    if not catalog_item or not catalog_item.get('visibleToStudents') or not catalog_item.get('isActive'):
        raise ValueError('Document not available')

    if not auto_generate_enabled(catalog_item):
        raise ValueError('Auto-generation is not enabled for this document')

    try:
        document_type = DocumentType.objects.get(pk=pk, is_active=True)
    except DocumentType.DoesNotExist:
        raise ValueError('Document not available')

    template = catalog_service._default_template(document_type)
    if not template or not template.file_template:
        raise ValueError('No template file is configured for this document')

    fulfilled_with_output = (
        DocumentRequest.objects.filter(
            target_student_profile=profile,
            document_type=document_type,
            status=DocumentRequest.Status.FULFILLED,
            outputs__isnull=False,
        )
        .prefetch_related('outputs')
        .order_by('-fulfilled_at', '-created_at')
        .first()
    )
    if fulfilled_with_output:
        output = fulfilled_with_output.outputs.order_by('-generated_at').first()
        if output:
            return _build_response(fulfilled_with_output, output, http_request)

    pending = DocumentRequest.objects.filter(
        target_student_profile=profile,
        document_type=document_type,
        status__in=PENDING_STATUSES,
    ).order_by('-created_at').first()

    config = catalog_item.get('config') or {}
    delivery = config.get('delivery') or {}
    online = delivery.get('online') or {}
    physical = delivery.get('physical') or {}
    delivery_method = 'pickup' if physical.get('enabled') and not online.get('enabled') else 'digital'

    now = timezone.now()
    if pending:
        req = pending
        req.status = DocumentRequest.Status.FULFILLED
        req.fulfilled_at = now
        req.reviewed_at = req.reviewed_at or now
        req.template = template
        meta = dict(req.metadata_json or {})
        meta.update({
            'deliveryMethod': delivery_method,
            'catalogServiceId': str(pk),
            'autoGenerated': True,
        })
        req.metadata_json = meta
        req.save(
            update_fields=[
                'status',
                'fulfilled_at',
                'reviewed_at',
                'template',
                'metadata_json',
                'updated_at',
            ],
        )
    else:
        req = DocumentRequest.objects.create(
            document_type=document_type,
            template=template,
            requested_by=user,
            target_user=user,
            target_student_profile=profile,
            status=DocumentRequest.Status.FULFILLED,
            submitted_at=now,
            reviewed_at=now,
            fulfilled_at=now,
            metadata_json={
                'deliveryMethod': delivery_method,
                'catalogServiceId': str(pk),
                'autoGenerated': True,
            },
        )

    with template.file_template.open('rb') as source:
        content = source.read()

    file_name = os.path.basename(template.file_template.name)
    content_hash = hashlib.sha256(content + str(req.pk).encode() + uuid.uuid4().bytes).hexdigest()
    output = DocumentOutput(
        document_request=req,
        format=_output_format_from_name(file_name),
        sha256_hash=content_hash,
        generated_by=user,
    )
    output.file.save(file_name, ContentFile(content), save=True)

    return _build_response(req, output, http_request)
