from django.urls import path

from .import_views import (
    SrfImportAuditListView,
    SrfImportBatchDetailView,
    SrfImportBatchListView,
    SrfImportExecuteView,
    SrfImportMappingProfileListCreateView,
    SrfImportPreviewView,
    SrfImportRollbackView,
    SrfImportSchemaView,
    SrfImportUploadView,
    SrfImportWipeFinancialModuleView,
)
from .config_views import (
    SrfConfigAuditLogView,
    SrfConfigExamPeriodDetailView,
    SrfConfigExamPeriodListCreateView,
    SrfConfigInstallmentPlanDetailView,
    SrfConfigInstallmentPlanListCreateView,
    SrfConfigSimulateView,
    SrfConfigTemplatePreviewView,
    SrfConfigWorkspaceView,
    SrfNotificationTemplateDetailView,
    SrfNotificationTemplateListCreateView,
    SrfRestrictionPolicyView,
    SrfWarningTierDetailView,
    SrfWarningTierListCreateView,
)
from .views import (
    SrfAnalyticsView,
    SrfDashboardSummaryView,
    SrfExamPeriodDetailView,
    SrfExamPeriodListCreateView,
    SrfKpiCardsView,
    SrfMyFinancialDetailView,
    SrfPaymentProofDetailView,
    SrfPaymentProofQueueView,
    SrfPaymentProofReviewView,
    SrfPaymentProofSubmitView,
    SrfRefreshStudentView,
    SrfRiskAlertsView,
    SrfRiskScanView,
    SrfSetupInstallmentPlanView,
    SrfStudentAccessView,
    SrfStudentFinancialDetailView,
    SrfStudentFinancialListView,
    SrfAdminChatOpenView,
    SrfStudentChatView,
)

urlpatterns = [
    path('dashboard/summary', SrfDashboardSummaryView.as_view(), name='srf-dashboard-summary'),
    path('dashboard/kpi', SrfKpiCardsView.as_view(), name='srf-dashboard-kpi'),
    path('analytics', SrfAnalyticsView.as_view(), name='srf-analytics'),
    path('students', SrfStudentFinancialListView.as_view(), name='srf-students-list'),
    path('student/me', SrfMyFinancialDetailView.as_view(), name='srf-student-me'),
    path('chat/open', SrfStudentChatView.as_view(), name='srf-student-chat-open'),
    path(
        'students/<int:account_id>/chat/open',
        SrfAdminChatOpenView.as_view(),
        name='srf-admin-chat-open',
    ),
    path('students/<int:account_id>', SrfStudentFinancialDetailView.as_view(), name='srf-student-detail'),
    path('students/<int:student_id>/refresh', SrfRefreshStudentView.as_view(), name='srf-student-refresh'),
    path('payment-proofs', SrfPaymentProofQueueView.as_view(), name='srf-payment-proofs'),
    path('payment-proofs/submit', SrfPaymentProofSubmitView.as_view(), name='srf-payment-proof-submit'),
    path('payment-proofs/<int:proof_id>', SrfPaymentProofDetailView.as_view(), name='srf-payment-proof-detail'),
    path('payment-proofs/<int:proof_id>/review', SrfPaymentProofReviewView.as_view(), name='srf-payment-proof-review'),
    path('exam-periods', SrfExamPeriodListCreateView.as_view(), name='srf-exam-periods'),
    path('exam-periods/<int:period_id>', SrfExamPeriodDetailView.as_view(), name='srf-exam-period-detail'),
    # Operations configuration workspace
    path('config/workspace', SrfConfigWorkspaceView.as_view(), name='srf-config-workspace'),
    path('config/warning-tiers', SrfWarningTierListCreateView.as_view(), name='srf-config-warning-tiers'),
    path('config/warning-tiers/<int:tier_id>', SrfWarningTierDetailView.as_view(), name='srf-config-warning-tier-detail'),
    path('config/restriction-policy', SrfRestrictionPolicyView.as_view(), name='srf-config-restriction-policy'),
    path('config/templates', SrfNotificationTemplateListCreateView.as_view(), name='srf-config-templates'),
    path('config/templates/<int:template_id>', SrfNotificationTemplateDetailView.as_view(), name='srf-config-template-detail'),
    path('config/exam-periods', SrfConfigExamPeriodListCreateView.as_view(), name='srf-config-exam-periods'),
    path('config/exam-periods/<int:period_id>', SrfConfigExamPeriodDetailView.as_view(), name='srf-config-exam-period-detail'),
    path('config/installment-plans', SrfConfigInstallmentPlanListCreateView.as_view(), name='srf-config-installment-plans'),
    path('config/installment-plans/<int:template_id>', SrfConfigInstallmentPlanDetailView.as_view(), name='srf-config-installment-plan-detail'),
    path('config/audit-log', SrfConfigAuditLogView.as_view(), name='srf-config-audit-log'),
    path('config/simulate', SrfConfigSimulateView.as_view(), name='srf-config-simulate'),
    path('config/preview-template', SrfConfigTemplatePreviewView.as_view(), name='srf-config-preview-template'),
    path('access', SrfStudentAccessView.as_view(), name='srf-student-access-self'),
    path('access/<int:student_id>', SrfStudentAccessView.as_view(), name='srf-student-access'),
    path('risk-alerts', SrfRiskAlertsView.as_view(), name='srf-risk-alerts'),
    path('risk-scan', SrfRiskScanView.as_view(), name='srf-risk-scan'),
    path('installment-plan', SrfSetupInstallmentPlanView.as_view(), name='srf-installment-plan'),
    # Financial Import Center
    path('imports/schema', SrfImportSchemaView.as_view(), name='srf-import-schema'),
    path('imports/batches', SrfImportBatchListView.as_view(), name='srf-import-batches'),
    path('imports/upload', SrfImportUploadView.as_view(), name='srf-import-upload'),
    path('imports/profiles', SrfImportMappingProfileListCreateView.as_view(), name='srf-import-profiles'),
    path('imports/batches/<uuid:batch_uuid>', SrfImportBatchDetailView.as_view(), name='srf-import-batch-detail'),
    path('imports/batches/<uuid:batch_uuid>/preview', SrfImportPreviewView.as_view(), name='srf-import-preview'),
    path('imports/batches/<uuid:batch_uuid>/execute', SrfImportExecuteView.as_view(), name='srf-import-execute'),
    path('imports/batches/<uuid:batch_uuid>/rollback', SrfImportRollbackView.as_view(), name='srf-import-rollback'),
    path('imports/batches/<uuid:batch_uuid>/audit', SrfImportAuditListView.as_view(), name='srf-import-audit'),
    path(
        'imports/reset-financial-module',
        SrfImportWipeFinancialModuleView.as_view(),
        name='srf-import-reset-financial-module',
    ),
]
