# Generated by Django 4.2.30 on 2026-06-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_intelligence', '0002_student_intelligence_scores'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentprofileindicator',
            new_name='profile_int_health__2e39bc_idx',
            old_name='profile_int_health_idx',
        ),
        migrations.RenameIndex(
            model_name='studentprofileindicator',
            new_name='profile_int_risk_ca_5a43f5_idx',
            old_name='profile_int_risk_cat_idx',
        ),
    ]
