# Generated by Django 4.2.30 on 2026-06-16 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=16)),
                ('template_code', models.CharField(blank=True, default='', max_length=128)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('error_message', models.TextField(blank=True, default='')),
                ('provider_response_json', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDigestBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=16)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-period_end'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationEventDedup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationProviderHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('channel', models.CharField(max_length=16)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('is_healthy', models.BooleanField(default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=16)),
                ('template_code', models.CharField(blank=True, default='', max_length=128)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('limit_value', models.PositiveIntegerField(default=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=128, unique=True)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push notification')], max_length=16)),
                ('category', models.CharField(choices=[('offers', 'Offers'), ('applications', 'Applications'), ('documents', 'Documents'), ('announcements', 'Announcements'), ('chat', 'Chat'), ('srf', 'SRF'), ('cv_analysis', 'CV Analysis'), ('interview_simulator', 'Interview Simulator'), ('system', 'System'), ('supervision', 'Supervision')], db_index=True, max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('html_file', models.CharField(blank=True, default='', max_length=255)),
                ('default_action_url', models.CharField(blank=True, default='', max_length=512)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(db_index=True, max_length=8)),
                ('subject_template', models.TextField()),
                ('body_html_template', models.TextField(blank=True, default='')),
                ('body_text_template', models.TextField(blank=True, default='')),
                ('in_app_title_template', models.TextField(blank=True, default='')),
                ('in_app_body_template', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='notificationpreference',
            name='uniq_preference_per_user_type_channel',
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=16),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='RECEIVED', max_length=16),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('offers', 'Offers'), ('applications', 'Applications'), ('documents', 'Documents'), ('announcements', 'Announcements'), ('chat', 'Chat'), ('srf', 'SRF'), ('cv_analysis', 'CV Analysis'), ('interview_simulator', 'Interview Simulator'), ('system', 'System'), ('supervision', 'Supervision')], db_index=True, default='system', max_length=32),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=8),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='provider_message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='template_code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='frequency',
            field=models.CharField(choices=[('REALTIME', 'Realtime'), ('DAILY_DIGEST', 'Daily digest'), ('WEEKLY_DIGEST', 'Weekly digest'), ('MONTHLY_DIGEST', 'Monthly digest'), ('NEVER', 'Never')], default='REALTIME', max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.SlugField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked'), ('FAILED', 'Failed'), ('RETRY_SCHEDULED', 'Retry scheduled'), ('CANCELLED', 'Cancelled'), ('SUPPRESSED', 'Suppressed'), ('BOUNCED', 'Bounced')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['status', '-triggered_at'], name='notificatio_status_82bd40_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecipient',
            index=models.Index(fields=['status', 'next_retry_at'], name='notificatio_status_5e8698_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'channel'), name='uniq_preference_per_user_category_channel'),
        ),
        migrations.AddField(
            model_name='notificationtemplatetranslation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='notifications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notificationratelimit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rate_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='notificationproviderhealth',
            constraint=models.UniqueConstraint(fields=('provider', 'channel'), name='uniq_provider_channel_health'),
        ),
        migrations.AddField(
            model_name='notificationeventdedup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dedup_records', to='notifications.notificationevent'),
        ),
        migrations.AddField(
            model_name='notificationdigestbatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_digest_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationdeliverylog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notificationevent'),
        ),
        migrations.AddField(
            model_name='notificationdeliverylog',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notificationrecipient'),
        ),
        migrations.AddField(
            model_name='notificationdeliverylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_delivery_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='digest_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='notifications.notificationdigestbatch'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplatetranslation',
            constraint=models.UniqueConstraint(fields=('template', 'language'), name='uniq_template_language'),
        ),
        migrations.AddIndex(
            model_name='notificationratelimit',
            index=models.Index(fields=['user', 'channel', 'window_start'], name='notificatio_user_id_e25443_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationratelimit',
            index=models.Index(fields=['channel', 'template_code', 'window_start'], name='notificatio_channel_a7816d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdigestbatch',
            index=models.Index(fields=['user', 'frequency', '-period_end'], name='notificatio_user_id_6c0294_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdigestbatch',
            index=models.Index(fields=['status', '-created_at'], name='notificatio_status_377857_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(fields=['channel', 'status', '-created_at'], name='notificatio_channel_5d7a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(fields=['template_code', '-created_at'], name='notificatio_templat_1779be_idx'),
        ),
    ]
