# Generated by Django 4.2.29 on 2026-06-16 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_enterprise_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCategoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('offers', 'Offers'), ('applications', 'Applications'), ('documents', 'Documents'), ('announcements', 'Announcements'), ('chat', 'Chat'), ('srf', 'SRF'), ('cv_analysis', 'CV Analysis'), ('interview_simulator', 'Interview Simulator'), ('system', 'System'), ('supervision', 'Supervision')], max_length=32, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('email_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('digest_enabled', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Email category config',
                'verbose_name_plural': 'Email category configs',
                'ordering': ['sort_order', 'category'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('mock', 'Mock (development)'), ('sendgrid', 'SendGrid'), ('ses', 'Amazon SES'), ('mailgun', 'Mailgun'), ('smtp', 'SMTP')], default='mock', max_length=32)),
                ('api_key', models.CharField(blank=True, default='', max_length=512)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('endpoint', models.CharField(blank=True, default='', max_length=512)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(blank=True, null=True)),
                ('smtp_user', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connected', 'Connected'), ('connection_error', 'Connection error')], default='disconnected', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Email provider config',
                'verbose_name_plural': 'Email provider configs',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_email_enabled', models.BooleanField(default=True)),
                ('default_sender_name', models.CharField(default='Digital Talent Center', max_length=255)),
                ('default_sender_email', models.EmailField(default='noreply@talent-center.ma', max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('default_language', models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', max_length=8)),
                ('rate_limit_email_per_hour', models.PositiveIntegerField(default=20)),
                ('rate_limit_global_per_minute', models.PositiveIntegerField(default=100)),
                ('max_retry_attempts', models.PositiveSmallIntegerField(default=5)),
                ('queue_max_size', models.PositiveIntegerField(default=10000)),
                ('digest_schedule', models.CharField(default='0 8 * * *', max_length=64)),
                ('bounce_handling_enabled', models.BooleanField(default=True)),
                ('unsubscribe_rules_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Platform email settings',
                'verbose_name_plural': 'Platform email settings',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailSenderIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('module', models.CharField(choices=[('general', 'General'), ('offers', 'Internship offers'), ('applications', 'Applications'), ('documents', 'Documents'), ('announcements', 'Announcements'), ('chat', 'Chat'), ('srf', 'SRF'), ('cv_analysis', 'CV analysis'), ('interview_simulator', 'Interview simulator'), ('system', 'System')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending verification'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['module', 'display_name'],
                'abstract': False,
                'indexes': [models.Index(fields=['module', 'status'], name='notificatio_module_5b8928_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailSystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('change_type', models.CharField(choices=[('general', 'General settings'), ('provider', 'Provider'), ('sender', 'Sender identity'), ('category', 'Category'), ('template', 'Template'), ('advanced', 'Advanced settings')], db_index=True, max_length=16)),
                ('field_name', models.CharField(max_length=128)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_system_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['change_type', '-changed_at'], name='notificatio_change__1cf052_idx')],
            },
        ),
    ]
