# Generated by Django 4.2.30 on 2026-06-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_email_system_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcategoryconfig',
            name='category',
            field=models.CharField(choices=[('offers', 'Offers'), ('applications', 'Applications'), ('documents', 'Documents'), ('announcements', 'Announcements'), ('chat', 'Chat'), ('srf', 'SRF'), ('cv_analysis', 'CV Analysis'), ('interview_simulator', 'Interview Simulator'), ('career_coach', 'Career Coach'), ('system', 'System'), ('supervision', 'Supervision')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('offers', 'Offers'), ('applications', 'Applications'), ('documents', 'Documents'), ('announcements', 'Announcements'), ('chat', 'Chat'), ('srf', 'SRF'), ('cv_analysis', 'CV Analysis'), ('interview_simulator', 'Interview Simulator'), ('career_coach', 'Career Coach'), ('system', 'System'), ('supervision', 'Supervision')], db_index=True, default='system', max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='category',
            field=models.CharField(choices=[('offers', 'Offers'), ('applications', 'Applications'), ('documents', 'Documents'), ('announcements', 'Announcements'), ('chat', 'Chat'), ('srf', 'SRF'), ('cv_analysis', 'CV Analysis'), ('interview_simulator', 'Interview Simulator'), ('career_coach', 'Career Coach'), ('system', 'System'), ('supervision', 'Supervision')], db_index=True, max_length=32),
        ),
    ]
