# Generated by Django 4.2.29 on 2026-06-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_unread_composite_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_recip_arch_read_idx',
        ),
    ]
