import { FunctionComponent } from 'react';
import { useTranslation } from 'react-i18next';
import {
  AlertTriangle,
  Calendar,
  CheckCircle2,
  Clock,
  FileCheck,
  Inbox,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import AdminKpiGrid from '../../ui/AdminKpiGrid';
import AdminKpiStatCard from '../../ui/AdminKpiStatCard';
import { AdminKpiGridSkeleton } from '../../ui/AdminKpiGridSkeleton';
import type { DocumentsDashboardData } from '../types';

interface Props {
  summary: DocumentsDashboardData['summary'] | null;
  loading?: boolean;
  onNavigate?: (key: string) => void;
}

const KPI_CONFIG: {
  key: string;
  icon: LucideIcon;
  field: keyof DocumentsDashboardData['summary'];
  suffix?: string;
  accent: string;
  accentBg: string;
}[] = [
  {
    key: 'active',
    icon: Inbox,
    field: 'activeRequests',
    accent: 'var(--admin-brand)',
    accentBg: 'var(--admin-brand-muted)',
  },
  {
    key: 'pendingApprovals',
    icon: Clock,
    field: 'pendingApprovals',
    accent: '#d97706',
    accentBg: 'rgba(217, 119, 6, 0.1)',
  },
  {
    key: 'slaAtRisk',
    icon: AlertTriangle,
    field: 'slaAtRisk',
    accent: '#dc2626',
    accentBg: 'rgba(220, 38, 38, 0.1)',
  },
  {
    key: 'reservationsToday',
    icon: Calendar,
    field: 'reservationsToday',
    accent: '#0891b2',
    accentBg: 'rgba(8, 145, 178, 0.1)',
  },
  {
    key: 'autoGenerated',
    icon: Zap,
    field: 'autoGeneratedWeek',
    accent: '#7c3aed',
    accentBg: 'rgba(124, 58, 237, 0.1)',
  },
  {
    key: 'rejectionRate',
    icon: FileCheck,
    field: 'rejectionRate',
    suffix: '%',
    accent: '#64748b',
    accentBg: 'rgba(100, 116, 139, 0.12)',
  },
  {
    key: 'avgProcessing',
    icon: CheckCircle2,
    field: 'avgProcessingHours',
    suffix: 'h',
    accent: '#059669',
    accentBg: 'rgba(5, 150, 105, 0.1)',
  },
];

const DocumentsKpiStrip: FunctionComponent<Props> = ({ summary, loading, onNavigate }) => {
  const { t } = useTranslation();

  if (loading && !summary) {
    return <AdminKpiGridSkeleton count={7} columns={4} />;
  }

  return (
    <AdminKpiGrid columns={4}>
      {KPI_CONFIG.map(({ key, icon, field, suffix, accent, accentBg }, index) => (
        <AdminKpiStatCard
          key={key}
          index={index}
          icon={icon}
          label={t(`admin.documentsModule.kpi.${key}`)}
          value={`${summary?.[field] ?? 0}${suffix ?? ''}`}
          accent={accent}
          accentBg={accentBg}
          onClick={() => onNavigate?.(key)}
        />
      ))}
    </AdminKpiGrid>
  );
};

export default DocumentsKpiStrip;
