import { CSSProperties, FunctionComponent, useMemo } from 'react';
import { motion } from 'framer-motion';
import {
  AlertTriangle,
  Calendar,
  CheckCircle2,
  Clock,
  FileCheck,
  Inbox,
  type LucideIcon,
} from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { easePremium } from '../../dashboard/ui/animations';
import { AdminStudentsStatsSkeleton } from '../../ui/AdminSectionSkeleton';
import type { DocumentsDashboardData } from '../types';

interface Props {
  summary: DocumentsDashboardData['summary'] | null;
  loading?: boolean;
  onNavigate?: (key: string) => void;
}

interface DocumentKpiCard {
  key: string;
  Icon: LucideIcon;
  value: string;
  badge: string;
  accent: string;
  accentBg: string;
  piePercent?: number;
}

const clampPercent = (value: number) => Math.min(100, Math.max(0, Math.round(value)));

const DocumentsKpiStrip: FunctionComponent<Props> = ({ summary, loading, onNavigate }) => {
  const { t } = useTranslation();

  const cards = useMemo<DocumentKpiCard[]>(() => {
    const data = summary ?? {
      activeRequests: 0,
      pendingApprovals: 0,
      slaAtRisk: 0,
      reservationsToday: 0,
      autoGeneratedWeek: 0,
      rejectionRate: 0,
      avgProcessingHours: 0,
    };
    const active = Math.max(data.activeRequests, 0);
    const ratioOfActive = (value: number) =>
      active > 0 ? Math.round((value / active) * 100) : 0;

    return [
      {
        key: 'active',
        Icon: Inbox,
        value: String(data.activeRequests),
        badge: t('admin.documentsModule.kpi.badges.active'),
        accent: '#3b82f6',
        accentBg: 'rgba(59, 130, 246, 0.16)',
      },
      {
        key: 'pendingApprovals',
        Icon: Clock,
        value: String(data.pendingApprovals),
        badge: t('admin.documentsModule.kpi.badges.ofActive', {
          percent: ratioOfActive(data.pendingApprovals),
        }),
        accent: '#f59e0b',
        accentBg: 'rgba(245, 158, 11, 0.16)',
        piePercent: ratioOfActive(data.pendingApprovals),
      },
      {
        key: 'slaAtRisk',
        Icon: AlertTriangle,
        value: String(data.slaAtRisk),
        badge: t('admin.documentsModule.kpi.badges.atRisk'),
        accent: '#ef4444',
        accentBg: 'rgba(239, 68, 68, 0.16)',
        piePercent: ratioOfActive(data.slaAtRisk),
      },
      {
        key: 'reservationsToday',
        Icon: Calendar,
        value: String(data.reservationsToday),
        badge: t('admin.documentsModule.kpi.badges.today'),
        accent: '#06b6d4',
        accentBg: 'rgba(6, 182, 212, 0.16)',
      },
      {
        key: 'rejectionRate',
        Icon: FileCheck,
        value: `${data.rejectionRate}%`,
        badge: t('admin.documentsModule.kpi.badges.rejection'),
        accent: '#64748b',
        accentBg: 'rgba(100, 116, 139, 0.16)',
        piePercent: clampPercent(data.rejectionRate),
      },
      {
        key: 'avgProcessing',
        Icon: CheckCircle2,
        value: `${data.avgProcessingHours}h`,
        badge: t('admin.documentsModule.kpi.badges.avgTime'),
        accent: '#22c55e',
        accentBg: 'rgba(34, 197, 94, 0.16)',
      },
    ];
  }, [summary, t]);

  if (loading && !summary) {
    return <AdminStudentsStatsSkeleton count={6} withPiePattern="all-but-first" />;
  }

  return (
    <div className="admin-students-stats-grid admin-students-stats-grid--center-last">
      {cards.map((card, index) => {
        const title = t(`admin.documentsModule.kpi.${card.key}`);
        const isClickable = Boolean(onNavigate);

        return (
          <motion.article
            key={card.key}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.05, duration: 0.4, ease: easePremium }}
            whileHover={{ scale: 1.02, y: -2 }}
            className={[
              'admin-students-stat-card',
              card.piePercent != null ? 'admin-students-stat-card--rate' : '',
              isClickable ? 'cursor-pointer' : '',
            ]
              .filter(Boolean)
              .join(' ')}
            style={
              {
                '--student-stat-accent': card.accent,
                '--student-stat-accent-bg': card.accentBg,
              } as CSSProperties
            }
            onClick={isClickable ? () => onNavigate?.(card.key) : undefined}
            role={isClickable ? 'button' : undefined}
            tabIndex={isClickable ? 0 : undefined}
            onKeyDown={
              isClickable
                ? (e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault();
                      onNavigate?.(card.key);
                    }
                  }
                : undefined
            }
          >
            <div className="admin-students-stat-card__body">
              <div className="admin-students-stat-card__head">
                <span className="admin-students-stat-card__icon" aria-hidden>
                  <card.Icon className="h-5 w-5" strokeWidth={1.8} />
                </span>
                <p className="admin-students-stat-card__title">{title}</p>
              </div>
              <p className="admin-students-stat-card__value">{card.value}</p>
              <span className="admin-students-stat-card__badge">{card.badge}</span>
            </div>
            {card.piePercent != null ? (
              <div
                className="admin-students-stat-card__pie"
                style={{ '--student-stat-pie': card.piePercent } as CSSProperties}
                role="img"
                aria-label={`${title} ${card.piePercent}%`}
              >
                <span className="admin-students-stat-card__pie-inner">{card.piePercent}%</span>
              </div>
            ) : null}
          </motion.article>
        );
      })}
    </div>
  );
};

export default DocumentsKpiStrip;
