import { FunctionComponent } from 'react';
import { useTranslation } from 'react-i18next';
import {
  AlertTriangle,
  Calendar,
  CheckCircle2,
  Clock,
  FileCheck,
  Inbox,
  Zap,
} from 'lucide-react';
import type { DocumentsDashboardData } from '../types';

interface Props {
  summary: DocumentsDashboardData['summary'] | null;
  loading?: boolean;
  onNavigate?: (key: string) => void;
}

const KPI_KEYS: {
  key: string;
  icon: typeof Inbox;
  field: keyof DocumentsDashboardData['summary'];
  suffix?: string;
}[] = [
  { key: 'active', icon: Inbox, field: 'activeRequests' },
  { key: 'pendingApprovals', icon: Clock, field: 'pendingApprovals' },
  { key: 'slaAtRisk', icon: AlertTriangle, field: 'slaAtRisk' },
  { key: 'reservationsToday', icon: Calendar, field: 'reservationsToday' },
  { key: 'autoGenerated', icon: Zap, field: 'autoGeneratedWeek' },
  { key: 'rejectionRate', icon: FileCheck, field: 'rejectionRate', suffix: '%' },
  { key: 'avgProcessing', icon: CheckCircle2, field: 'avgProcessingHours', suffix: 'h' },
];

const DocumentsKpiStrip: FunctionComponent<Props> = ({ summary, loading, onNavigate }) => {
  const { t } = useTranslation();

  return (
    <div className="admin-doc-kpi-grid">
      {KPI_KEYS.map(({ key, icon: Icon, field, suffix }) => (
        <button
          key={key}
          type="button"
          className="admin-doc-kpi-card"
          onClick={() => onNavigate?.(key)}
          disabled={loading}
        >
          <span className="admin-doc-kpi-card__icon">
            <Icon className="h-5 w-5" aria-hidden />
          </span>
          <span className="admin-doc-kpi-card__value">
            {loading ? '—' : `${summary?.[field] ?? 0}${suffix ?? ''}`}
          </span>
          <span className="admin-doc-kpi-card__label">{t(`admin.documentsModule.kpi.${key}`)}</span>
        </button>
      ))}
    </div>
  );
};

export default DocumentsKpiStrip;
