import type { StatPageChartId } from './types';

const C = {
  brand: '#2563eb',
  brandLight: '#60a5fa',
  success: '#16a34a',
  warning: '#d97706',
  danger: '#dc2626',
  violet: '#7c3aed',
  slate: '#64748b',
  cyan: '#0891b2',
};

export interface StatChartConfig {
  title: string;
  subtitle: string;
  type: 'bar' | 'line' | 'donut';
  ariaLabel: string;
  labels?: readonly string[];
  series?: { key: string; label: string; color: string; values: number[] }[];
  segments?: { key: string; label: string; value: number; color: string }[];
  stacked?: boolean;
  showArea?: boolean;
  max?: number;
}

export const STAT_PAGE_CHARTS: Record<StatPageChartId, StatChartConfig> = {
  'students-total-enrollment': {
    title: 'Students by field',
    subtitle: 'Share of each program among all students',
    type: 'donut',
    ariaLabel: 'Donut chart of students by field of study',
    segments: [],
  },
  'students-active-split': {
    title: 'Activity split',
    subtitle: 'Active and inactive students out of the total',
    type: 'donut',
    ariaLabel: 'Donut chart of active and inactive students',
    segments: [
      { key: 'active', label: 'Active', value: 892, color: C.success },
      { key: 'inactive', label: 'Inactive', value: 156, color: C.slate },
    ],
  },
  'students-without-internship': {
    title: 'Without internship',
    subtitle: 'Students with vs without internship (total population)',
    type: 'donut',
    ariaLabel: 'Donut chart of students with and without internship',
    segments: [
      { key: 'with', label: 'With internship', value: 0, color: '#6366f1' },
      { key: 'without', label: 'Without internship', value: 0, color: C.warning },
    ],
  },
  'students-with-internship': {
    title: 'With internship',
    subtitle: 'Students with vs without internship (total population)',
    type: 'donut',
    ariaLabel: 'Donut chart of students with and without internship',
    segments: [
      { key: 'with', label: 'With internship', value: 0, color: '#6366f1' },
      { key: 'without', label: 'Without internship', value: 0, color: C.warning },
    ],
  },
  'students-engagement-distribution': {
    title: 'Engagement levels',
    subtitle: 'High, medium and low engagement out of all students',
    type: 'donut',
    ariaLabel: 'Donut chart of student engagement levels',
    segments: [
      { key: 'high', label: 'High', value: 312, color: C.success },
      { key: 'medium', label: 'Medium', value: 428, color: C.brand },
      { key: 'low', label: 'Low', value: 118, color: C.warning },
    ],
  },
  'students-internship-split': {
    title: 'Internship assignment',
    subtitle: 'Students with vs without internship',
    type: 'donut',
    ariaLabel: 'Donut chart of students with and without internship',
    segments: [
      { key: 'with', label: 'With internship', value: 0, color: '#6366f1' },
      { key: 'without', label: 'Without internship', value: 0, color: C.warning },
    ],
  },
  'offers-all-status': {
    title: 'Offers by status',
    subtitle: 'Share of each offer state',
    type: 'donut',
    ariaLabel: 'Donut chart of internship offers by status',
    segments: [
      { key: 'active', label: 'Active', value: 42, color: C.success },
      { key: 'draft', label: 'Draft', value: 18, color: C.warning },
      { key: 'expired', label: 'Expired', value: 12, color: C.danger },
      { key: 'closed', label: 'Closed', value: 6, color: C.slate },
    ],
  },
  'offers-active-companies': {
    title: 'Top companies',
    subtitle: 'Applications on active offers',
    type: 'bar',
    ariaLabel: 'Bar chart of applications by company',
    labels: ['TechCorp', 'DataHub', 'WebAgency', 'CloudTech', 'SecureNet'],
    series: [{ key: 'apps', label: 'Applications', color: C.brand, values: [45, 32, 28, 22, 25] }],
  },
  'offers-expired-timeline': {
    title: 'Expiration timeline',
    subtitle: 'Offers expired per month',
    type: 'line',
    ariaLabel: 'Line chart of expired offers over time',
    labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    series: [{ key: 'expired', label: 'Expired', color: C.danger, values: [3, 5, 4, 8, 6, 12] }],
  },
  'offers-draft-monthly': {
    title: 'Draft activity',
    subtitle: 'Draft offers created per month',
    type: 'bar',
    ariaLabel: 'Bar chart of draft offers by month',
    labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    series: [{ key: 'drafts', label: 'Drafts', color: C.warning, values: [4, 6, 5, 9, 7, 11] }],
  },
  'offers-closed-reasons': {
    title: 'Closure reasons',
    subtitle: 'Why offers were closed',
    type: 'bar',
    ariaLabel: 'Bar chart of offer closure reasons',
    labels: ['Filled', 'Cancelled', 'Merged', 'Other'],
    series: [{ key: 'count', label: 'Offers', color: C.slate, values: [14, 6, 3, 2] }],
  },
  'offers-applications-volume': {
    title: 'Application volume',
    subtitle: 'Applicants per offer bucket',
    type: 'bar',
    ariaLabel: 'Bar chart of application volume',
    labels: ['0-10', '11-25', '26-40', '40+'],
    series: [{ key: 'offers', label: 'Offers', color: '#2563eb', values: [8, 14, 11, 5] }],
  },
  'srf-paid-overview': {
    title: 'Payment overview',
    subtitle: 'Paid vs outstanding balance',
    type: 'donut',
    ariaLabel: 'Donut chart of SRF payment status for paid students',
    segments: [
      { key: 'paid', label: 'Fully paid', value: 520, color: C.success },
      { key: 'credit', label: 'Credit balance', value: 42, color: C.cyan },
    ],
  },
  'srf-unpaid-amounts': {
    title: 'Unpaid amounts',
    subtitle: 'Amount due by class group',
    type: 'bar',
    ariaLabel: 'Bar chart of unpaid SRF amounts',
    labels: ['ING', 'MGT', 'DS', 'Other'],
    series: [{ key: 'mad', label: 'MAD due', color: C.danger, values: [180, 95, 72, 48] }],
    max: 200,
  },
  'srf-partially-paid': {
    title: 'Partial payments',
    subtitle: 'Due vs paid amounts (k MAD)',
    type: 'bar',
    ariaLabel: 'Grouped bar chart of partial SRF payments',
    labels: ['ING-A', 'ING-B', 'MGT', 'DS'],
    series: [
      { key: 'due', label: 'Due', color: C.warning, values: [45, 38, 52, 41] },
      { key: 'paid', label: 'Paid', color: C.success, values: [28, 22, 35, 30] },
    ],
  },
  'srf-pending-queue': {
    title: 'Validation queue',
    subtitle: 'Pending payments awaiting review',
    type: 'bar',
    ariaLabel: 'Bar chart of pending SRF validations by day',
    labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    series: [{ key: 'pending', label: 'Pending', color: C.brand, values: [12, 18, 9, 15, 11] }],
  },
  'srf-late-timeline': {
    title: 'Late payments',
    subtitle: 'Late cases detected per week',
    type: 'line',
    ariaLabel: 'Line chart of late SRF payments',
    labels: ['W1', 'W2', 'W3', 'W4', 'W5', 'W6'],
    series: [{ key: 'late', label: 'Late cases', color: C.danger, values: [8, 12, 9, 15, 11, 14] }],
  },
  'srf-blocked-trend': {
    title: 'Blocked accounts',
    subtitle: 'Blocks issued over recent weeks',
    type: 'line',
    ariaLabel: 'Line chart of blocked student accounts',
    labels: ['W1', 'W2', 'W3', 'W4', 'W5', 'W6'],
    series: [{ key: 'blocked', label: 'Blocked', color: C.violet, values: [3, 5, 4, 7, 5, 6] }],
  },
  'srf-exempted-reasons': {
    title: 'Exemption reasons',
    subtitle: 'Why students were exempted',
    type: 'donut',
    ariaLabel: 'Donut chart of SRF exemption reasons',
    segments: [
      { key: 'scholarship', label: 'Scholarship', value: 24, color: C.success },
      { key: 'hardship', label: 'Hardship', value: 11, color: C.warning },
      { key: 'admin', label: 'Admin decision', value: 8, color: C.slate },
    ],
  },
  'encadrants-department-load': {
    title: 'Load by program',
    subtitle: 'Encadrants per program out of the total',
    type: 'donut',
    ariaLabel: 'Donut chart of encadrants by program',
    segments: [],
  },
  'encadrants-top-assigned': {
    title: 'Top assignments',
    subtitle: 'Students assigned per encadrant out of all assignments',
    type: 'donut',
    ariaLabel: 'Donut chart of assigned students by encadrant',
    segments: [],
  },
  'encadrants-reports-split': {
    title: 'Reports in progress',
    subtitle: 'Student reports submitted by encadrants (coming soon)',
    type: 'donut',
    ariaLabel: 'Encadrant reports status',
    segments: [],
  },
  'encadrants-meetings-weekly': {
    title: 'Student assignments',
    subtitle: 'Encadrants with vs without assigned students',
    type: 'donut',
    ariaLabel: 'Donut chart of encadrants with assigned students',
    segments: [],
  },
  'announcements-type-mix': {
    title: 'Announcement types',
    subtitle: 'Distribution by category',
    type: 'donut',
    ariaLabel: 'Donut chart of announcement types',
    segments: [
      { key: 'info', label: 'Information', value: 28, color: C.brand },
      { key: 'urgent', label: 'Urgent', value: 12, color: C.danger },
      { key: 'event', label: 'Event', value: 18, color: C.violet },
    ],
  },
  'announcements-active-split': {
    title: 'Active vs scheduled',
    subtitle: 'Currently live announcements',
    type: 'donut',
    ariaLabel: 'Donut chart of active announcements',
    segments: [
      { key: 'live', label: 'Live', value: 22, color: C.success },
      { key: 'scheduled', label: 'Scheduled', value: 9, color: C.warning },
    ],
  },
  'documents-status-mix': {
    title: 'Document requests',
    subtitle: 'Status distribution',
    type: 'donut',
    ariaLabel: 'Donut chart of document request statuses',
    segments: [
      { key: 'pending', label: 'Pending', value: 45, color: C.warning },
      { key: 'validated', label: 'Validated', value: 128, color: C.success },
      { key: 'rejected', label: 'Rejected', value: 18, color: C.danger },
    ],
  },
  'documents-pending-age': {
    title: 'Pending age',
    subtitle: 'How long requests have waited',
    type: 'bar',
    ariaLabel: 'Bar chart of pending document age',
    labels: ['<24h', '1-3d', '3-7d', '>7d'],
    series: [{ key: 'count', label: 'Requests', color: C.warning, values: [18, 14, 9, 4] }],
  },
  'documents-validated-trend': {
    title: 'Validations trend',
    subtitle: 'Documents validated per day (last week)',
    type: 'line',
    ariaLabel: 'Line chart of document validations',
    labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    series: [{ key: 'validated', label: 'Validated', color: C.success, values: [12, 18, 15, 22, 19, 8, 6] }],
  },
  'documents-rejected-reasons': {
    title: 'Rejection reasons',
    subtitle: 'Top reasons for rejection',
    type: 'bar',
    ariaLabel: 'Bar chart of document rejection reasons',
    labels: ['Incomplete', 'Invalid', 'Duplicate', 'Other'],
    series: [{ key: 'count', label: 'Rejections', color: C.danger, values: [9, 5, 3, 1] }],
  },
  'history-total-actions': {
    title: 'Activity volume',
    subtitle: 'Platform actions over the last 7 days',
    type: 'line',
    ariaLabel: 'Line chart of total platform actions',
    labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    series: [{ key: 'actions', label: 'Actions', color: C.brand, values: [240, 310, 285, 360, 320, 180, 150] }],
    max: 400,
  },
  'history-students': {
    title: 'Student actions',
    subtitle: 'CRUD and profile updates per day',
    type: 'line',
    ariaLabel: 'Line chart of student history actions',
    labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    series: [{ key: 'student', label: 'Actions', color: C.brandLight, values: [42, 58, 51, 64, 55, 28, 22] }],
  },
  'history-applications': {
    title: 'Application funnel',
    subtitle: 'Applications by stage',
    type: 'bar',
    ariaLabel: 'Bar chart of application funnel stages',
    labels: ['Submitted', 'Review', 'Interview', 'Accepted'],
    series: [{ key: 'apps', label: 'Applications', color: C.brand, values: [120, 86, 52, 38] }],
  },
  'history-srf': {
    title: 'SRF payments',
    subtitle: 'Payment-related actions per week',
    type: 'line',
    ariaLabel: 'Line chart of SRF payment history',
    labels: ['W1', 'W2', 'W3', 'W4', 'W5', 'W6'],
    series: [{ key: 'pay', label: 'Payments', color: C.success, values: [88, 102, 95, 118, 110, 125] }],
  },
  'history-documents': {
    title: 'Document activity',
    subtitle: 'Validation workflow events',
    type: 'line',
    ariaLabel: 'Line chart of document history',
    labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    series: [{ key: 'docs', label: 'Events', color: C.cyan, values: [32, 45, 38, 52, 48, 20, 15] }],
  },
  'history-chat': {
    title: 'Chat activity',
    subtitle: 'Messages sent per day',
    type: 'line',
    ariaLabel: 'Line chart of chat messages',
    labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    series: [{ key: 'msgs', label: 'Messages', color: C.violet, values: [420, 510, 480, 560, 520, 280, 210] }],
    max: 600,
  },
  'dashboard-students-fields': {
    title: 'Students by field',
    subtitle: 'Distribution across study fields',
    type: 'donut',
    ariaLabel: 'Donut chart of students by field',
    segments: [
      { key: 'ing', label: 'Engineering', value: 420, color: C.brand },
      { key: 'mgt', label: 'Management', value: 280, color: C.violet },
      { key: 'ds', label: 'Data Science', value: 198, color: C.cyan },
    ],
  },
  'dashboard-encadrants-dept': {
    title: 'Encadrants by department',
    subtitle: 'Supervisor distribution',
    type: 'bar',
    ariaLabel: 'Bar chart of encadrants by department',
    labels: ['IT', 'Business', 'Eng.', 'Design'],
    series: [{ key: 'enc', label: 'Encadrants', color: '#7c3aed', values: [18, 12, 15, 8] }],
  },
  'dashboard-admins-roles': {
    title: 'Admin roles',
    subtitle: 'Platform administrators by role',
    type: 'donut',
    ariaLabel: 'Donut chart of administrator roles',
    segments: [
      { key: 'super', label: 'Super Admin', value: 4, color: C.brand },
      { key: 'stage', label: 'Stage', value: 8, color: C.success },
      { key: 'finance', label: 'Finance', value: 5, color: C.warning },
      { key: 'other', label: 'Other', value: 6, color: C.slate },
    ],
  },
  'dashboard-without-internship': {
    title: 'Without internship',
    subtitle: 'Breakdown by support need',
    type: 'bar',
    ariaLabel: 'Bar chart of students without internship',
    labels: ['Searching', 'Support', 'Hold'],
    series: [{ key: 'stu', label: 'Students', color: '#ea580c', values: [72, 38, 20] }],
  },
  'dashboard-active-offers-apps': {
    title: 'Applications',
    subtitle: 'Applicants on active offers',
    type: 'bar',
    ariaLabel: 'Bar chart of applications on active offers',
    labels: ['Offer A', 'Offer B', 'Offer C', 'Offer D', 'Offer E'],
    series: [{ key: 'apps', label: 'Applicants', color: '#4f46e5', values: [38, 32, 28, 24, 20] }],
  },
  'dashboard-ongoing-funnel': {
    title: 'Application funnel',
    subtitle: 'Ongoing applications by stage',
    type: 'bar',
    ariaLabel: 'Bar chart of ongoing application stages',
    labels: ['Pending', 'Review', 'Accepted'],
    series: [{ key: 'flow', label: 'Applications', color: '#0891b2', values: [86, 54, 32] }],
  },
  'dashboard-documents-pending': {
    title: 'Pending validations',
    subtitle: 'Documents awaiting review by age',
    type: 'bar',
    ariaLabel: 'Bar chart of pending document validations',
    labels: ['<24h', '1-3d', '3-7d', '>7d'],
    series: [{ key: 'pend', label: 'Pending', color: C.warning, values: [22, 16, 11, 6] }],
  },
  'dashboard-srf-unpaid': {
    title: 'Unpaid SRF',
    subtitle: 'Outstanding amount by class (k MAD)',
    type: 'bar',
    ariaLabel: 'Bar chart of unpaid SRF amounts',
    labels: ['ING', 'MGT', 'DS'],
    series: [{ key: 'due', label: 'Due', color: C.danger, values: [95, 62, 48] }],
  },
  'admins-role-distribution': {
    title: 'Role distribution',
    subtitle: 'Administrators by assigned role',
    type: 'donut',
    ariaLabel: 'Donut chart of administrator roles',
    segments: [
      { key: 'stage', label: 'Stage', value: 12, color: C.brand },
      { key: 'finance', label: 'Finance', value: 8, color: C.success },
      { key: 'docs', label: 'Documents', value: 6, color: C.warning },
      { key: 'comm', label: 'Communication', value: 5, color: C.violet },
    ],
  },
};
