# Generated by Django 4.2.30 on 2026-06-24 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_coach', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiconversation',
            new_name='ai_conversa_user_id_1811da_idx',
            old_name='ai_conv_user_sess_created_idx',
        ),
    ]
