# Generated by Django 4.2.30 on 2026-06-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_coach', '0003_aicoachsession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aicoachsession',
            new_name='ai_coach_se_user_id_37c5df_idx',
            old_name='ai_coach_sess_user_arch_upd_idx',
        ),
    ]
