# Generated by Django 4.2.30 on 2026-08-28 19:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_alter_documenttype_service_config_json'),
        ('admin_management', '0016_filiere_specialization_domains'),
        ('chat', '0006_repair_offer_admin_inbox_archives'),
        ('encadrant', '0004_meeting_jitsi_session'),
        ('accounts_et_roles', '0006_student_internship_status_fields'),
        ('stage', '0007_semantic_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('MEETING', 'Meeting'), ('DEADLINE', 'Deadline'), ('EVALUATION', 'Evaluation'), ('MILESTONE', 'Internship milestone'), ('ADMINISTRATIVE', 'Administrative'), ('FINANCE', 'SRF / Finance'), ('REMINDER', 'Reminder'), ('OUT_OF_OFFICE', 'Out of office'), ('OTHER', 'Other')], db_index=True, default='MEETING', max_length=20)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('TENTATIVE', 'Tentative'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='CONFIRMED', max_length=16)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=16)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private — organizer only'), ('PARTICIPANTS', 'Participants only'), ('SUPERVISION', 'Participants, supervising encadrant and admins')], db_index=True, default='PARTICIPANTS', max_length=16)),
                ('source', models.CharField(choices=[('NATIVE', 'Created in the calendar'), ('MEETING', 'Projected from a supervision meeting')], db_index=True, default='NATIVE', max_length=16)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('timezone', models.CharField(default='Africa/Casablanca', help_text='IANA zone the event was authored in, e.g. Africa/Casablanca.', max_length=64)),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('external_meeting_url', models.URLField(blank=True, default='', max_length=512)),
                ('recurrence_original_start', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, help_text='Existing chat thread for this event — never created in duplicate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='chat.conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, help_text='Existing supervision meeting supplying the video room.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='encadrant.meeting')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('recurrence_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_overrides', to='agenda.calendarevent')),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='stage.offerapplication')),
                ('related_assignment', models.ForeignKey(blank=True, help_text='Internship / supervision assignment this event belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='admin_management.assignment')),
                ('related_document_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='documents.documentrequest')),
                ('related_encadrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='admin_management.encadrantprofile')),
                ('related_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='stage.internshipoffer')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='encadrant.report')),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='accounts_et_roles.studentprofile')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='encadrant.task')),
            ],
            options={
                'ordering': ['start_at', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minutes_before', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(43200)])),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email')], default='IN_APP', max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='agenda.calendarevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['minutes_before'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventReminderDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_start', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='agenda.eventreminder')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRecurrenceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_start', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_exceptions', to='agenda.calendarevent')),
            ],
            options={
                'ordering': ['occurrence_start'],
            },
        ),
        migrations.CreateModel(
            name='EventRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='WEEKLY', max_length=12)),
                ('interval', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('by_weekdays', models.JSONField(blank=True, default=list, help_text='WEEKLY only. ISO-style indexes with Monday = 0.')),
                ('by_month_day', models.PositiveSmallIntegerField(blank=True, help_text='MONTHLY / YEARLY only. Defaults to the master start day.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('until_at', models.DateTimeField(blank=True, null=True)),
                ('count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence', to='agenda.calendarevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ORGANIZER', 'Organizer'), ('REQUIRED', 'Required attendee'), ('OPTIONAL', 'Optional attendee')], default='REQUIRED', max_length=16)),
                ('response', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('TENTATIVE', 'Tentative')], db_index=True, default='PENDING', max_length=16)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='agenda.calendarevent')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='Africa/Casablanca', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('is_available', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='eventreminderdispatch',
            constraint=models.UniqueConstraint(fields=('reminder', 'occurrence_start'), name='uniq_agenda_reminder_dispatch'),
        ),
        migrations.AddIndex(
            model_name='eventreminder',
            index=models.Index(fields=['event', 'is_active'], name='agenda_even_event_i_6e54bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventreminder',
            constraint=models.UniqueConstraint(fields=('event', 'user', 'minutes_before', 'channel'), name='uniq_agenda_reminder_per_user'),
        ),
        migrations.AddIndex(
            model_name='eventrecurrenceexception',
            index=models.Index(fields=['series', 'occurrence_start'], name='agenda_even_series__9a3508_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventrecurrenceexception',
            constraint=models.UniqueConstraint(fields=('series', 'occurrence_start'), name='uniq_agenda_recurrence_exception'),
        ),
        migrations.AddConstraint(
            model_name='eventrecurrence',
            constraint=models.CheckConstraint(check=models.Q(('until_at__isnull', True), ('count__isnull', True), _connector='OR'), name='agenda_recurrence_until_xor_count'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['user', 'response'], name='agenda_even_user_id_81f0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event', 'role'], name='agenda_even_event_i_afc0ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='uniq_agenda_participant_per_event'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['organizer', 'start_at'], name='agenda_cale_organiz_380a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['start_at', 'end_at'], name='agenda_cale_start_a_c74941_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_type', 'start_at'], name='agenda_cale_event_t_c8cd2f_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['status', 'start_at'], name='agenda_cale_status_9680c9_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['related_student', 'start_at'], name='agenda_cale_related_06b7a6_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['related_encadrant', 'start_at'], name='agenda_cale_related_6579ec_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['related_assignment', 'start_at'], name='agenda_cale_related_3ef92d_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['recurrence_parent', 'recurrence_original_start'], name='agenda_cale_recurre_dd29c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.CheckConstraint(check=models.Q(('end_at__gte', models.F('start_at'))), name='agenda_event_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(condition=models.Q(('recurrence_parent__isnull', False)), fields=('recurrence_parent', 'recurrence_original_start'), name='uniq_agenda_recurrence_override'),
        ),
        migrations.AddIndex(
            model_name='availabilityrule',
            index=models.Index(fields=['user', 'is_active'], name='agenda_avai_user_id_bc31a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityrule',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='agenda_availability_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='availabilityrule',
            constraint=models.UniqueConstraint(fields=('user', 'weekday', 'start_time', 'end_time'), name='uniq_agenda_availability_window'),
        ),
        migrations.AddIndex(
            model_name='availabilityexception',
            index=models.Index(fields=['user', 'start_at'], name='agenda_avai_user_id_8c485a_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityexception',
            constraint=models.CheckConstraint(check=models.Q(('end_at__gt', models.F('start_at'))), name='agenda_availability_exception_end_after_start'),
        ),
    ]
