# Generated by Django 4.2.29 on 2026-05-18 13:09

from django.db import migrations, models
import django.db.models.deletion


def _seed_esca_academic(apps, schema_editor):
    # Deferred to 0013 — seed uses name_fr/name_en added in 0011.
    pass


class Migration(migrations.Migration):
    # PostgreSQL: avoid "pending trigger events" when seeding before deferred indexes.
    atomic = False

    dependencies = [
        ('admin_management', '0002_adminprofile_scope_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('name_i18n', models.JSONField(blank=True, default=dict)),
                ('year_number', models.PositiveSmallIntegerField(default=1)),
                ('has_sectors', models.BooleanField(default=False, help_text='Whether this level offers specialization tracks.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['filiere', 'sort_order', 'year_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('name_i18n', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='admin_management.academiclevel')),
            ],
            options={
                'ordering': ['academic_level', 'sort_order', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Format: 2025-2026', max_length=16, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=32)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'Academic years',
                'ordering': ['-start_year'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['sort_order', 'code']},
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='scope_level_ids',
            field=models.JSONField(blank=True, default=list, help_text='AcademicLevel IDs this admin may operate on.'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='scope_sector_ids',
            field=models.JSONField(blank=True, default=list, help_text='AcademicSector IDs this admin may operate on.'),
        ),
        migrations.AddField(
            model_name='encadrantprofile',
            name='scope_academic_years',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='encadrantprofile',
            name='scope_filiere_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='encadrantprofile',
            name='scope_level_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='encadrantprofile',
            name='scope_sector_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='filiere',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='filiere',
            name='program_family',
            field=models.CharField(blank=True, choices=[('PGE', 'Programme Grande École'), ('LME', 'Licence en Management des Entreprises'), ('IBA', 'International Business Administration'), ('MASTER', 'Master')], db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='filiere',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='level',
            field=models.CharField(blank=True, default='', help_text='Denormalized level code for legacy filters.', max_length=64),
        ),
        migrations.CreateModel(
            name='InternshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('name_i18n', models.JSONField(blank=True, default=dict)),
                ('duration_hint', models.CharField(blank=True, default='', max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_types', to='admin_management.academiclevel')),
                ('academic_sector', models.ForeignKey(blank=True, help_text='When set, this type applies only to students in that sector.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internship_types', to='admin_management.academicsector')),
            ],
            options={
                'ordering': ['academic_level', 'sort_order', 'code'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='academiclevel',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_levels', to='admin_management.filiere'),
        ),
        migrations.AddField(
            model_name='adminroleassignment',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='admin_management.academiclevel'),
        ),
        migrations.AddField(
            model_name='adminroleassignment',
            name='academic_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='admin_management.academicsector'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='admin_management.academiclevel'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='academic_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='admin_management.academicsector'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='academic_year_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='admin_management.academicyear'),
        ),
        migrations.AddConstraint(
            model_name='internshiptype',
            constraint=models.UniqueConstraint(fields=('academic_level', 'academic_sector', 'code'), name='uniq_internship_type_per_level_sector'),
        ),
        migrations.AddConstraint(
            model_name='academicsector',
            constraint=models.UniqueConstraint(fields=('academic_level', 'code'), name='uniq_sector_per_level'),
        ),
        migrations.AddConstraint(
            model_name='academiclevel',
            constraint=models.UniqueConstraint(fields=('filiere', 'code'), name='uniq_academic_level_per_filiere'),
        ),
        migrations.RunPython(_seed_esca_academic, migrations.RunPython.noop),
    ]
