# Generated by Django 4.2.29 on 2026-05-18 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_et_roles', '0004_esca_academic_hierarchy'),
        ('admin_management', '0006_specialization_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_type', models.CharField(choices=[('NO_MATCHING_ENCADRANT', 'No matching encadrant'), ('ENCADRANT_CAPACITY_EXCEEDED', 'Encadrant capacity exceeded'), ('SPECIALIZATION_MISMATCH', 'Specialization mismatch'), ('SCOPE_CONFLICT', 'Scope conflict'), ('MISSING_STUDENT_DATA', 'Missing student data'), ('DUPLICATE_ASSIGNMENT', 'Duplicate assignment'), ('UNBALANCED_DISTRIBUTION', 'Unbalanced distribution'), ('NO_AVAILABLE_ENCADRANTS', 'No available encadrants'), ('ORPHANED_STUDENT', 'Orphaned student')], db_index=True, max_length=48)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], db_index=True, default='OPEN', max_length=16)),
                ('academic_year', models.CharField(db_index=True, max_length=16)),
                ('issue_details', models.JSONField(blank=True, default=dict)),
                ('academic_scope', models.JSONField(blank=True, default=dict)),
                ('recommendation_key', models.CharField(blank=True, default='', max_length=64)),
                ('recommendation_params', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('resolution_action', models.CharField(blank=True, default='', max_length=32)),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
            ],
            options={
                'ordering': ['-detected_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentCaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('DETECTED', 'Detected'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored'), ('REOPENED', 'Reopened'), ('MANUAL_ASSIGN', 'Manual assign'), ('OVERRIDE', 'Override'), ('ENGINE_RERUN', 'Engine re-run'), ('AUTO_CLEARED', 'Auto cleared')], db_index=True, max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Assignment case histories',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RenameIndex(
            model_name='assignment',
            new_name='admin_manag_is_lock_16f8ae_idx',
            old_name='admin_manag_is_lock_8a1f2c_idx',
        ),
        migrations.AlterField(
            model_name='specializationdomain',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='Lowercase tokens for matching student skills and interests.'),
        ),
        migrations.AlterField(
            model_name='specializationdomain',
            name='master_tracks',
            field=models.JSONField(blank=True, default=list, help_text='Optional master track codes (ASCM, MD, MRH, …).'),
        ),
        migrations.AlterField(
            model_name='specializationdomain',
            name='program_families',
            field=models.JSONField(blank=True, default=list, help_text='ESCA program families (PGE, LME, IBA, MASTER). Empty = all programs.'),
        ),
        migrations.AddField(
            model_name='assignmentcasehistory',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='admin_management.assignmentcase'),
        ),
        migrations.AddField(
            model_name='assignmentcasehistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_case_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentcase',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='admin_management.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentcase',
            name='encadrant_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_cases', to='admin_management.encadrantprofile'),
        ),
        migrations.AddField(
            model_name='assignmentcase',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_assignment_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentcase',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_cases', to='accounts_et_roles.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='assignmentcase',
            index=models.Index(fields=['academic_year', 'status', 'severity'], name='admin_manag_academi_9a6187_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentcase',
            index=models.Index(fields=['case_type', 'status'], name='admin_manag_case_ty_e12456_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentcase',
            index=models.Index(fields=['student_profile', 'academic_year'], name='admin_manag_student_3f5094_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentcase',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'IN_PROGRESS'])), fields=('fingerprint', 'academic_year'), name='uniq_open_assignment_case_fingerprint'),
        ),
    ]
