# Generated by Django 4.2.29 on 2026-05-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0008_encadrant_supervised_internship_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentcasehistory',
            name='case',
        ),
        migrations.RemoveField(
            model_name='assignmentcasehistory',
            name='performed_by',
        ),
        migrations.DeleteModel(
            name='AssignmentCase',
        ),
        migrations.DeleteModel(
            name='AssignmentCaseHistory',
        ),
    ]
