# Generated by Django 4.2.30 on 2026-06-15 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_management', '0009_compliance_and_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('name_i18n', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='academiclevel',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='filiere',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='internshiptype',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='program_family',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Dynamic program family code (PGE, LME, IBA, MASTER, …).', max_length=32),
        ),
        migrations.CreateModel(
            name='AcademicStructureAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(db_index=True, max_length=32)),
                ('entity_id', models.PositiveIntegerField(db_index=True)),
                ('entity_label', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ARCHIVED', 'Archived'), ('ACTIVATED', 'Activated'), ('DEACTIVATED', 'Deactivated'), ('REORDERED', 'Reordered')], db_index=True, max_length=16)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('summary', models.CharField(blank=True, default='', max_length=512)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_structure_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='admin_manag_entity__a5cfc2_idx'), models.Index(fields=['-created_at'], name='admin_manag_created_6a636b_idx')],
            },
        ),
    ]
