# Generated by Django 4.2.30 on 2026-06-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0011_academic_entity_bilingual_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicstructureauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted'), ('ACTIVATED', 'Activated'), ('DEACTIVATED', 'Deactivated'), ('REORDERED', 'Reordered')], db_index=True, max_length=16),
        ),
    ]
