# Generated by Django 4.2.29 on 2026-05-17 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_ciphertext', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', 'is_current'], name='authenticat_user_id_5b618a_idx')],
            },
        ),
    ]
