# Generated by Django 4.2.29 on 2026-05-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_studentcredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcredential',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
