/** Re-export admin-aligned tokens for the student dashboard. */
export {
  STUDENT_SURFACE_CARD,
  STUDENT_SURFACE_CARD_INTERACTIVE,
  STUDENT_PRIMARY_BUTTON,
  STUDENT_SECONDARY_BUTTON,
  STUDENT_SECTION_LINK,
  STUDENT_EMPTY_STATE,
  STUDENT_TEXT_PRIMARY,
  STUDENT_TEXT_SECONDARY,
  STUDENT_TEXT_MUTED,
  STUDENT_PAGE_CONTAINER,
} from '../../design-system/studentTokens';
