from django.urls import path

from .views import (
    AnnouncementActionView,
    AnnouncementAnalyticsView,
    AnnouncementAttachmentUploadView,
    AnnouncementBulkActionView,
    AnnouncementCoverUploadView,
    AnnouncementDashboardView,
    AnnouncementDetailView,
    AnnouncementEmailPreviewView,
    AnnouncementEngagementView,
    AnnouncementInsightsView,
    AnnouncementListCreateView,
    AnnouncementScheduledDashboardView,
    AnnouncementTypeListView,
    AnnouncementTypeManageView,
    AnnouncementTypeSeedView,
    StudentAnnouncementBookmarkView,
    StudentAnnouncementChatView,
    StudentAnnouncementDetailView,
    StudentAnnouncementEngageView,
    StudentAnnouncementFeedView,
    StudentAnnouncementSavedFeedView,
)

urlpatterns = [
    path('admin/announcements/dashboard', AnnouncementDashboardView.as_view()),
    path('admin/announcements/scheduled', AnnouncementScheduledDashboardView.as_view()),
    path('admin/announcements', AnnouncementListCreateView.as_view()),
    path('admin/announcements/bulk', AnnouncementBulkActionView.as_view()),
    path('admin/announcements/analytics', AnnouncementAnalyticsView.as_view()),
    path('admin/announcements/insights', AnnouncementInsightsView.as_view()),
    path('admin/announcements/engagement', AnnouncementEngagementView.as_view()),
    path('admin/announcements/types', AnnouncementTypeListView.as_view()),
    path('admin/announcements/types/seed', AnnouncementTypeSeedView.as_view()),
    path('admin/announcements/types/<int:pk>', AnnouncementTypeManageView.as_view()),
    path('admin/announcements/<uuid:uuid>/cover', AnnouncementCoverUploadView.as_view()),
    path('admin/announcements/<uuid:uuid>/email-preview', AnnouncementEmailPreviewView.as_view()),
    path('admin/announcements/<uuid:uuid>/attachments', AnnouncementAttachmentUploadView.as_view()),
    path('admin/announcements/<uuid:uuid>/<str:action>', AnnouncementActionView.as_view()),
    path('admin/announcements/<uuid:uuid>', AnnouncementDetailView.as_view()),
    path('student/announcements/feed', StudentAnnouncementFeedView.as_view()),
    path('student/announcements/saved', StudentAnnouncementSavedFeedView.as_view()),
    path('student/announcements/<uuid:uuid>/bookmark', StudentAnnouncementBookmarkView.as_view()),
    path('student/announcements/<uuid:uuid>/engage', StudentAnnouncementEngageView.as_view()),
    path('student/announcements/<uuid:uuid>/chat', StudentAnnouncementChatView.as_view()),
    path('student/announcements/<uuid:uuid>', StudentAnnouncementDetailView.as_view()),
]
