# Generated by Django 4.2.30 on 2026-06-21 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stage', '0005_offerapplication_status_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contract'), ('PARTNERSHIP', 'Partnership agreement'), ('VERIFICATION', 'Verification document'), ('OTHER', 'Other')], db_index=True, max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='companies/documents/%Y/%m/')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('EMAIL', 'Email'), ('CALL', 'Call'), ('MEETING', 'Meeting'), ('VISIT', 'Visit'), ('OTHER', 'Other')], db_index=True, max_length=16)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('PARTNER', 'Partner'), ('PARENT', 'Parent company'), ('SUBSIDIARY', 'Subsidiary'), ('CLIENT', 'Client'), ('SUPPLIER', 'Supplier')], max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('new_scheduled_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(blank=True, default='', max_length=16)),
                ('new_status', models.CharField(db_index=True, max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(default='INFO', max_length=16)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookRetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='companycontact',
            options={'ordering': ['-is_primary', 'full_name']},
        ),
        migrations.AlterModelOptions(
            name='companystatushistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-scheduled_at']},
        ),
        migrations.AlterModelOptions(
            name='interviewfeedback',
            options={},
        ),
        migrations.AlterModelOptions(
            name='interviewresult',
            options={},
        ),
        migrations.AlterModelOptions(
            name='matchingweightconfig',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='offercontenthistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='offerrecommendation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='offerversion',
            options={'ordering': ['-version_number']},
        ),
        migrations.AlterModelOptions(
            name='pipelinecolumn',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='slarule',
            options={'ordering': ['entity_type', 'threshold_hours']},
        ),
        migrations.AlterModelOptions(
            name='slaviolation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='webhookdelivery',
            options={},
        ),
        migrations.AlterModelOptions(
            name='webhookevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='webhooksubscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='offerapplication',
            name='uniq_active_application_per_student_offer',
        ),
        migrations.RenameIndex(
            model_name='applicationstatushistory',
            new_name='stage_appli_applica_f75497_idx',
            old_name='stage_appli_applica_s_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationstatushistory',
            new_name='stage_appli_new_sta_620412_idx',
            old_name='stage_appli_new_st_idx',
        ),
        migrations.RenameIndex(
            model_name='matchinghistory',
            new_name='stage_match_student_d98b57_idx',
            old_name='stage_match_student_idx',
        ),
        migrations.RenameIndex(
            model_name='matchinghistory',
            new_name='stage_match_offer_i_bfc926_idx',
            old_name='stage_match_offer_idx',
        ),
        migrations.RenameIndex(
            model_name='matchinghistory',
            new_name='stage_match_trigger_37381d_idx',
            old_name='stage_match_trigger_idx',
        ),
        migrations.RenameIndex(
            model_name='offerimportjob',
            new_name='stage_offer_status_095549_idx',
            old_name='stage_offer_status_i_idx',
        ),
        migrations.RenameIndex(
            model_name='offerimportjob',
            new_name='stage_offer_detecte_1c79b6_idx',
            old_name='stage_offer_detecte_idx',
        ),
        migrations.RenameIndex(
            model_name='offerstatushistory',
            new_name='stage_offer_offer_i_99cf7c_idx',
            old_name='stage_offer_offer_s_idx',
        ),
        migrations.RenameIndex(
            model_name='offerstatushistory',
            new_name='stage_offer_new_sta_8bc47c_idx',
            old_name='stage_offer_new_st_idx',
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('VERIFIED', 'Verified'), ('PENDING_VERIFICATION', 'Pending verification'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived'), ('BLACKLISTED', 'Blacklisted')], db_index=True, default='PENDING_VERIFICATION', max_length=24),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('PHONE', 'Phone'), ('VIDEO', 'Video'), ('ONSITE', 'On-site'), ('PANEL', 'Panel'), ('SIMULATOR', 'Interview simulator')], default='VIDEO', max_length=16),
        ),
        migrations.AlterField(
            model_name='interview',
            name='simulator_session_id',
            field=models.CharField(blank=True, default='', help_text='INTEGRATION POINT: Interview Simulator session ID', max_length=128),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('RESCHEDULED', 'Rescheduled'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], db_index=True, default='SCHEDULED', max_length=16),
        ),
        migrations.AlterField(
            model_name='interviewresult',
            name='outcome',
            field=models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PENDING', 'Pending'), ('HOLD', 'Hold')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='offerimportjob',
            name='detected_platform',
            field=models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('INDEED', 'Indeed'), ('REKRUTE', 'Rekrute'), ('EMPLOI_MA', 'Emploi.ma'), ('NOVOJOB', 'Novojob'), ('COMPANY_WEBSITE', 'Company website'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=32),
        ),
        migrations.AlterField(
            model_name='offerrecommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('FOR_YOU', 'Recommended for you'), ('TRENDING', 'Trending'), ('RECENT', 'Recently published'), ('URGENT', 'Urgent opportunity'), ('PROFILE', 'Based on profile'), ('APPLICATIONS', 'Based on applications'), ('SIMILAR_STUDENTS', 'Similar students')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='offertargetingrule',
            name='rule_type',
            field=models.CharField(choices=[('FILIERE', 'Filière'), ('CLASS_GROUP', 'Class group'), ('LEVEL', 'Education level'), ('INTERNSHIP_TYPE', 'Internship type'), ('SKILL', 'Skill'), ('LANGUAGE', 'Language'), ('AVAILABILITY', 'Availability'), ('LOCATION', 'Location'), ('CUSTOM', 'Custom')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='entity_type',
            field=models.CharField(choices=[('APPLICATION', 'Application'), ('CONVERSATION', 'Conversation'), ('INTERVIEW', 'Interview'), ('OFFER_REVIEW', 'Offer review')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='slaviolation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated')], db_index=True, default='OPEN', max_length=16),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='event_types',
            field=models.JSONField(default=list, help_text='List of event codes to subscribe'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status', 'name'], name='stage_compa_status_bf67ef_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['sector', 'status'], name='stage_compa_sector_d995c0_idx'),
        ),
        migrations.AddIndex(
            model_name='offerrecommendation',
            index=models.Index(fields=['student_profile', 'recommendation_type', '-score'], name='stage_offer_student_f423d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='offerapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('SUBMITTED', 'UNDER_REVIEW', 'SHORTLISTED', 'INTERVIEW', 'ACCEPTED', 'OFFER_ACCEPTED', 'INTERNSHIP_STARTED'))), fields=('student_profile', 'offer'), name='uniq_active_application_per_student_offer'),
        ),
        migrations.AddField(
            model_name='webhookretry',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retries', to='stage.webhookdelivery'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stage.webhookdelivery'),
        ),
        migrations.AddField(
            model_name='interviewstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewstatushistory',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='stage.interview'),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_history', to='stage.interview'),
        ),
        migrations.AddField(
            model_name='companyrelationship',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='stage.company'),
        ),
        migrations.AddField(
            model_name='companyrelationship',
            name='related_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverse_relationships', to='stage.company'),
        ),
        migrations.AddField(
            model_name='companynote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companynote',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='stage.company'),
        ),
        migrations.AddField(
            model_name='companyinteraction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='stage.company'),
        ),
        migrations.AddField(
            model_name='companyinteraction',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='stage.company'),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='companyrelationship',
            constraint=models.UniqueConstraint(fields=('company', 'related_company', 'relationship_type'), name='uniq_company_relationship'),
        ),
    ]
