# Generated by Django 4.2.30 on 2026-06-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0006_companydocument_companyinteraction_companynote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('STUDENT', 'Student profile'), ('OFFER', 'Internship offer')], db_index=True, max_length=16)),
                ('entity_id', models.PositiveIntegerField(db_index=True)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=64)),
                ('source_text_hash', models.CharField(blank=True, default='', max_length=64)),
                ('vector_json', models.JSONField(default=list)),
                ('dimensions', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='stage_seman_entity__a1a3ec_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='semanticembedding',
            constraint=models.UniqueConstraint(fields=('entity_type', 'entity_id'), name='uniq_semantic_embedding_entity'),
        ),
    ]
