/** @deprecated Legacy list row — prefer DocumentRequestListItem */
export interface DocumentRequestRow {
  id: string;
  documentType: string;
  studentName: string;
  studentClass?: string;
  submissionDate: string;
  status: string;
}

/** @deprecated Legacy stat card */
export interface DocumentRequestStat {
  label: string;
  labelKey: string;
  statKey: string;
  value: string;
  icon: 'FileText' | 'Clock' | 'CheckCircle' | 'XCircle';
}

export type DocumentsListStatusFilter =
  | DocumentRequestStatus
  | 'Pending'
  | 'Validated'
  | 'Rejected'
  | 'pending'
  | 'validated'
  | 'rejected';

/** Document request workflow statuses (full lifecycle). */
export type DocumentRequestStatus =
  | 'draft'
  | 'submitted'
  | 'incomplete'
  | 'under_verification'
  | 'waiting_reservation'
  | 'reserved'
  | 'validated'
  | 'ready'
  | 'delivered'
  | 'rejected'
  | 'cancelled';

export type DocumentPriority = 'low' | 'normal' | 'high' | 'urgent';

export type DeliveryMethod = 'digital' | 'pickup' | 'mail' | 'signature';

export interface DocumentTypeConfig {
  id: string;
  code: string;
  nameKey: string;
  category: string;
  isActive: boolean;
  slaHours: number;
  requiresReservation: boolean;
  requiresApproval: boolean;
  autoGenerate: boolean;
  visibility: 'student' | 'staff' | 'internal';
  responsibleService: string;
  deliveryMethods: DeliveryMethod[];
  requiredAttachments: string[];
  formSchema: FormFieldSchema[];
}

export interface FormFieldSchema {
  name: string;
  labelKey: string;
  type: 'text' | 'number' | 'date' | 'boolean' | 'select' | 'file';
  required?: boolean;
  showWhen?: { field: string; equals: string };
  options?: { value: string; labelKey: string }[];
}

export interface StudentSummary {
  id: string;
  fullName: string;
  email: string;
  program: string;
  academicYear: string;
  classGroup: string;
  avatarInitials: string;
  avatarUrl?: string | null;
  srfClearance: boolean;
  encadrantName?: string;
}

export interface DocumentFilePreviewMeta {
  fileName: string;
  fileUrl?: string | null;
  fileType?: string;
  templateId?: string;
}

export interface GeneratedDocumentOutput {
  id: string;
  format: string;
  generatedAt: string;
  signed: boolean;
  fileName?: string;
  fileUrl?: string | null;
}

export interface WorkflowStep {
  id: string;
  code: string;
  labelKey: string;
  status: 'pending' | 'in_progress' | 'completed' | 'skipped' | 'failed';
  performedAt?: string;
  performedBy?: string;
  notes?: string;
}

export interface ReservationSlot {
  id: string;
  resourceName: string;
  resourceType: string;
  startAt: string;
  endAt: string;
  status: 'pending' | 'approved' | 'checked_in' | 'completed' | 'cancelled';
  location?: string;
}

export interface DocumentRequestListItem {
  id: string;
  uuid: string;
  reference: string;
  documentTypeCode: string;
  documentTypeName: string;
  student: StudentSummary;
  status: DocumentRequestStatus;
  priority: DocumentPriority;
  submittedAt?: string;
  slaDeadline?: string;
  slaPercent: number;
  assignedAgent?: string;
  serviceName: string;
  deliveryMethod: DeliveryMethod;
  hasReservation: boolean;
  autoGenerated: boolean;
}

export interface DocumentRequestDetail extends DocumentRequestListItem {
  reason?: string;
  documentTypeId?: string;
  autoGenerateEnabled?: boolean;
  templatePreview?: DocumentFilePreviewMeta | null;
  fields: { name: string; labelKey: string; value: string }[];
  attachments: { id: string; name: string; type: string; uploadedAt: string }[];
  workflowSteps: WorkflowStep[];
  reservation?: ReservationSlot;
  validationHistory: { at: string; by: string; action: string; note?: string }[];
  generatedOutputs: GeneratedDocumentOutput[];
  insights: string[];
  rejectionReason?: string;
}

export interface DocumentsDashboardData {
  summary: {
    activeRequests: number;
    pendingApprovals: number;
    slaAtRisk: number;
    reservationsToday: number;
    autoGeneratedWeek: number;
    rejectionRate: number;
    avgProcessingHours: number;
  };
  statusDistribution: { status: DocumentRequestStatus; count: number }[];
  serviceWorkload: { service: string; load: number; capacity: number }[];
  slaTrend: { day: string; onTime: number; breached: number }[];
  reservationOccupancy: { hour: string; percent: number }[];
  rejectionCauses: { cause: string; count: number }[];
  insights: { id: string; severity: 'info' | 'warning' | 'critical'; messageKey: string }[];
  recentRequests: DocumentRequestListItem[];
}

export interface PaginatedDocumentRequests {
  items: DocumentRequestListItem[];
  page: number;
  page_size: number;
  total: number;
  total_pages: number;
}

export interface DocumentListParams {
  page?: number;
  page_size?: number;
  search?: string;
  status?: DocumentRequestStatus;
  priority?: DocumentPriority;
  document_type?: string;
  service?: string;
  ordering?: string;
}

export interface AdministrativeResourceItem {
  id: string;
  code: string;
  name: string;
  resourceType: string;
  location: string;
  capacity: number;
  isActive: boolean;
  occupancyPercent: number;
}

export interface DocumentTemplateItem {
  id: string;
  code: string;
  name: string;
  documentTypeCode: string;
  language: string;
  isDefault: boolean;
  isActive: boolean;
  placeholders: string[];
}

export interface WorkflowDefinition {
  id: string;
  documentTypeCode: string;
  steps: { code: string; labelKey: string; requiredRole?: string }[];
  isActive: boolean;
}

export interface SlaRuleItem {
  id: string;
  name: string;
  documentTypeCode?: string;
  slaHours: number;
  escalationHours: number;
  autoAssign: boolean;
  reminderBeforeHours: number;
  isActive: boolean;
}

export interface DocumentsAnalyticsData {
  processingTimes: { service: string; avgHours: number }[];
  reservationSuccessRate: number;
  autoGenerationRate: number;
  bottlenecks: { step: string; avgHours: number }[];
  workloadHeatmap: { day: string; hour: number; load: number }[];
  deliveryAnalytics: { method: DeliveryMethod; count: number }[];
}
