# Generated by Django 4.2.30 on 2026-06-23 23:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv_builder', '0003_rename_cv_builder__student_share_idx_cv_builder__student_978c63_idx'),
        ('accounts_et_roles', '0005_student_internship_derived_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvStructuredData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_type', models.CharField(choices=[('builder', 'CV Builder'), ('pdf', 'PDF Upload'), ('docx', 'DOCX Upload'), ('profile_file', 'Profile CV File')], max_length=20)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('detected_languages', models.JSONField(blank=True, default=list)),
                ('structured_json', models.JSONField(blank=True, default=dict)),
                ('extraction_metadata', models.JSONField(blank=True, default=dict)),
                ('student_cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structured_extractions', to='cv_builder.studentcv')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_structured_data', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CvIntelligenceReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_type', models.CharField(choices=[('builder', 'CV Builder'), ('pdf', 'PDF Upload'), ('docx', 'DOCX Upload'), ('profile_file', 'Profile CV File')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=16)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('ai_model', models.CharField(blank=True, default='', max_length=64)),
                ('detected_languages', models.JSONField(blank=True, default=list)),
                ('global_score', models.PositiveSmallIntegerField(default=0)),
                ('skills_score', models.PositiveSmallIntegerField(default=0)),
                ('experience_score', models.PositiveSmallIntegerField(default=0)),
                ('education_score', models.PositiveSmallIntegerField(default=0)),
                ('formatting_score', models.PositiveSmallIntegerField(default=0)),
                ('ats_score', models.PositiveSmallIntegerField(default=0)),
                ('readiness_score', models.PositiveSmallIntegerField(default=0)),
                ('potential_score', models.PositiveSmallIntegerField(default=0)),
                ('semantic_profile_json', models.JSONField(blank=True, default=dict)),
                ('swot_json', models.JSONField(blank=True, default=dict)),
                ('ats_analysis_json', models.JSONField(blank=True, default=dict)),
                ('score_explanations_json', models.JSONField(blank=True, default=dict)),
                ('internship_matches_json', models.JSONField(blank=True, default=list)),
                ('missing_skills_json', models.JSONField(blank=True, default=list)),
                ('recommended_skills_json', models.JSONField(blank=True, default=list)),
                ('roadmap_json', models.JSONField(blank=True, default=list)),
                ('interview_prep_json', models.JSONField(blank=True, default=list)),
                ('dashboard_json', models.JSONField(blank=True, default=dict)),
                ('raw_response_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('previous_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor_reports', to='cv_intelligence.cvintelligencereport')),
                ('structured_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='cv_intelligence.cvstructureddata')),
                ('student_cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_reports', to='cv_builder.studentcv')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_intelligence_reports', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cvstructureddata',
            index=models.Index(fields=['student_profile', '-created_at'], name='cv_intellig_student_2a48d1_idx'),
        ),
        migrations.AddIndex(
            model_name='cvintelligencereport',
            index=models.Index(fields=['student_profile', '-analyzed_at'], name='cv_intellig_student_371333_idx'),
        ),
        migrations.AddIndex(
            model_name='cvintelligencereport',
            index=models.Index(fields=['student_cv', '-analyzed_at'], name='cv_intellig_student_062535_idx'),
        ),
    ]
