# Generated by Django 4.2.30 on 2026-06-24 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_intelligence', '0002_cv_analysis_versioning'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cvintelligencereport',
            new_name='cv_intellig_student_d18fa9_idx',
            old_name='cv_intel_stu_active_idx',
        ),
        migrations.RenameIndex(
            model_name='cvintelligencereport',
            new_name='cv_intellig_student_271235_idx',
            old_name='cv_intel_stu_hash_idx',
        ),
    ]
