# Generated by Django 4.2.30 on 2026-06-25 07:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_et_roles', '0006_student_internship_status_fields'),
        ('cv_intelligence', '0003_rename_cv_intel_stu_active_idx_cv_intellig_student_d18fa9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('offer_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('external_offer_url', models.URLField(blank=True, default='')),
                ('mode', models.CharField(choices=[('profile', 'Profile Interview'), ('offer', 'Offer Interview')], max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='draft', max_length=24)),
                ('language', models.CharField(default='fr', max_length=8)),
                ('llm_provider', models.CharField(blank=True, default='', max_length=64)),
                ('llm_model', models.CharField(blank=True, default='', max_length=128)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewTranscript',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('transcript_json', models.JSONField(blank=True, default=list)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='cv_intelligence.interviewsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('question_text', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=32)),
                ('rationale', models.TextField(blank=True, default='')),
                ('is_follow_up', models.BooleanField(default=False)),
                ('asked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cv_intelligence.interviewsession')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('strengths', models.TextField(blank=True, default='')),
                ('weaknesses', models.TextField(blank=True, default='')),
                ('missing_skills', models.TextField(blank=True, default='')),
                ('improvement_recommendations', models.TextField(blank=True, default='')),
                ('interview_readiness', models.CharField(blank=True, default='', max_length=64)),
                ('offer_comparison_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='cv_intelligence.interviewsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('communication_score', models.PositiveSmallIntegerField(default=0)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('technical_score', models.PositiveSmallIntegerField(default=0)),
                ('problem_solving_score', models.PositiveSmallIntegerField(default=0)),
                ('professionalism_score', models.PositiveSmallIntegerField(default=0)),
                ('soft_skills_score', models.PositiveSmallIntegerField(default=0)),
                ('language_quality_score', models.PositiveSmallIntegerField(default=0)),
                ('relevance_score', models.PositiveSmallIntegerField(default=0)),
                ('overall_score', models.PositiveSmallIntegerField(default=0)),
                ('strengths_json', models.JSONField(blank=True, default=list)),
                ('weaknesses_json', models.JSONField(blank=True, default=list)),
                ('missing_skills_json', models.JSONField(blank=True, default=list)),
                ('ideal_answer', models.TextField(blank=True, default='')),
                ('improvement_tips_json', models.JSONField(blank=True, default=list)),
                ('readiness_label', models.CharField(blank=True, default='', max_length=32)),
                ('is_final', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='cv_intelligence.interviewquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='cv_intelligence.interviewsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewContextSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_key', models.CharField(max_length=64)),
                ('summary_text', models.TextField(blank=True, default='')),
                ('source_hash', models.CharField(blank=True, default='', max_length=64)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_context_summaries', to='accounts_et_roles.studentprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=16)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=20)),
                ('communication_mode', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('voice_text', 'Voice + Text')], default='text', max_length=16)),
                ('interview_type', models.CharField(choices=[('hr', 'HR'), ('technical', 'Technical'), ('behavioral', 'Behavioral'), ('case_study', 'Case Study'), ('mixed', 'Mixed')], default='mixed', max_length=16)),
                ('recruiter_profile', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='cv_intelligence.interviewsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer_language', models.CharField(blank=True, default='', max_length=8)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='cv_intelligence.interviewquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['student_profile', '-created_at'], name='cv_intellig_student_4833d7_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['student_profile', 'status', '-created_at'], name='cv_intellig_student_79c1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['student_profile', 'mode', '-created_at'], name='cv_intellig_student_7fdf14_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['session', 'order_index'], name='cv_intellig_session_f80ee5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewquestion',
            unique_together={('session', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='interviewevaluation',
            index=models.Index(fields=['session', 'is_final', '-created_at'], name='cv_intellig_session_eceab0_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewevaluation',
            index=models.Index(fields=['question', '-created_at'], name='cv_intellig_questio_ab39d1_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewcontextsummary',
            index=models.Index(fields=['student_profile', 'summary_key'], name='cv_intellig_student_8c43ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewcontextsummary',
            unique_together={('student_profile', 'summary_key')},
        ),
    ]
