import type {
  AdministrativeResourceItem,
  DocumentRequestDetail,
  DocumentRequestListItem,
  DocumentRequestStatus,
  DocumentsAnalyticsData,
  DocumentsDashboardData,
  DocumentTemplateItem,
  DocumentTypeConfig,
  PaginatedDocumentRequests,
  SlaRuleItem,
  WorkflowDefinition,
} from '../types';

const students = [
  {
    id: 's1',
    fullName: 'Yasmine Benali',
    email: 'y.benali@esca.ma',
    program: 'Génie Informatique',
    academicYear: '2025-2026',
    classGroup: 'GI-3A',
    avatarInitials: 'YB',
    srfClearance: true,
    encadrantName: 'Dr. Amrani',
  },
  {
    id: 's2',
    fullName: 'Karim El Fassi',
    email: 'k.elfassi@esca.ma',
    program: 'Finance & Audit',
    academicYear: '2025-2026',
    classGroup: 'FA-2B',
    avatarInitials: 'KE',
    srfClearance: false,
    encadrantName: 'Mme. Berrada',
  },
  {
    id: 's3',
    fullName: 'Salma Idrissi',
    email: 's.idrissi@esca.ma',
    program: 'Marketing Digital',
    academicYear: '2025-2026',
    classGroup: 'MD-3A',
    avatarInitials: 'SI',
    srfClearance: true,
  },
  {
    id: 's4',
    fullName: 'Omar Tazi',
    email: 'o.tazi@esca.ma',
    program: 'Génie Industriel',
    academicYear: '2025-2026',
    classGroup: 'GI-2A',
    avatarInitials: 'OT',
    srfClearance: true,
    encadrantName: 'Pr. Zahraoui',
  },
];

export const DOCUMENT_TYPE_CONFIGS: DocumentTypeConfig[] = [
  {
    id: 'dt1',
    code: 'attestation-scolarite',
    nameKey: 'admin.documentsModule.types.attestationScolarite',
    category: 'ATTESTATION',
    isActive: true,
    slaHours: 48,
    requiresReservation: false,
    requiresApproval: true,
    autoGenerate: true,
    visibility: 'student',
    responsibleService: 'Scolarité',
    deliveryMethods: ['digital', 'pickup'],
    requiredAttachments: [],
    formSchema: [
      { name: 'academic_year', labelKey: 'admin.documentsModule.fields.academicYear', type: 'text', required: true },
      { name: 'purpose', labelKey: 'admin.documentsModule.fields.purpose', type: 'text' },
    ],
  },
  {
    id: 'dt2',
    code: 'convention-stage',
    nameKey: 'admin.documentsModule.types.conventionStage',
    category: 'CONVENTION',
    isActive: true,
    slaHours: 72,
    requiresReservation: true,
    requiresApproval: true,
    autoGenerate: false,
    visibility: 'student',
    responsibleService: 'Stages',
    deliveryMethods: ['signature', 'pickup'],
    requiredAttachments: ['company_letter', 'internship_offer'],
    formSchema: [
      { name: 'company_name', labelKey: 'admin.documentsModule.fields.companyName', type: 'text', required: true },
      { name: 'start_date', labelKey: 'admin.documentsModule.fields.startDate', type: 'date', required: true },
      { name: 'encadrant', labelKey: 'admin.documentsModule.fields.encadrant', type: 'text', showWhen: { field: 'document_type', equals: 'convention-stage' } },
    ],
  },
  {
    id: 'dt3',
    code: 'releve-notes',
    nameKey: 'admin.documentsModule.types.releveNotes',
    category: 'REPORT',
    isActive: true,
    slaHours: 24,
    requiresReservation: false,
    requiresApproval: true,
    autoGenerate: true,
    visibility: 'student',
    responsibleService: 'Scolarité',
    deliveryMethods: ['digital'],
    requiredAttachments: [],
    formSchema: [{ name: 'semester', labelKey: 'admin.documentsModule.fields.semester', type: 'select', required: true }],
  },
  {
    id: 'dt4',
    code: 'duplicata-diplome',
    nameKey: 'admin.documentsModule.types.duplicata',
    category: 'CERTIFICATE',
    isActive: true,
    slaHours: 120,
    requiresReservation: true,
    requiresApproval: true,
    autoGenerate: false,
    visibility: 'student',
    responsibleService: 'Archives',
    deliveryMethods: ['pickup', 'mail'],
    requiredAttachments: ['id_copy', 'payment_proof'],
    formSchema: [],
  },
];

function makeRequest(
  id: string,
  ref: string,
  typeIdx: number,
  studentIdx: number,
  status: DocumentRequestStatus,
  overrides: Partial<DocumentRequestListItem> = {},
): DocumentRequestListItem {
  const dt = DOCUMENT_TYPE_CONFIGS[typeIdx];
  const st = students[studentIdx];
  return {
    id,
    uuid: `uuid-${id}`,
    reference: ref,
    documentTypeCode: dt.code,
    documentTypeName: dt.code,
    student: st,
    status,
    priority: overrides.priority ?? 'normal',
    submittedAt: overrides.submittedAt ?? '2026-05-15T10:30:00',
    slaDeadline: overrides.slaDeadline ?? '2026-05-18T10:30:00',
    slaPercent: overrides.slaPercent ?? 65,
    assignedAgent: overrides.assignedAgent ?? 'Agent Scolarité',
    serviceName: dt.responsibleService,
    deliveryMethod: overrides.deliveryMethod ?? dt.deliveryMethods[0],
    hasReservation: overrides.hasReservation ?? dt.requiresReservation,
    autoGenerated: overrides.autoGenerated ?? dt.autoGenerate,
    ...overrides,
  };
}

export const MOCK_REQUESTS: DocumentRequestListItem[] = [
  makeRequest('req-001', 'DOC-2026-0142', 0, 0, 'under_verification', { slaPercent: 72, priority: 'high' }),
  makeRequest('req-002', 'DOC-2026-0141', 1, 1, 'waiting_reservation', { slaPercent: 88, hasReservation: false }),
  makeRequest('req-003', 'DOC-2026-0140', 2, 2, 'ready', { slaPercent: 100, autoGenerated: true }),
  makeRequest('req-004', 'DOC-2026-0139', 0, 3, 'submitted', { slaPercent: 15 }),
  makeRequest('req-005', 'DOC-2026-0138', 3, 0, 'reserved', { slaPercent: 45, hasReservation: true }),
  makeRequest('req-006', 'DOC-2026-0137', 1, 2, 'validated', { slaPercent: 90 }),
  makeRequest('req-007', 'DOC-2026-0136', 2, 1, 'rejected', { slaPercent: 100 }),
  makeRequest('req-008', 'DOC-2026-0135', 0, 2, 'delivered', { slaPercent: 100 }),
  makeRequest('req-009', 'DOC-2026-0134', 0, 1, 'incomplete', { slaPercent: 30 }),
  makeRequest('req-010', 'DOC-2026-0133', 1, 3, 'draft', { submittedAt: undefined, slaPercent: 0 }),
];

export function getMockRequestDetail(id: string): DocumentRequestDetail | null {
  const base = MOCK_REQUESTS.find((r) => r.id === id);
  if (!base) return null;
  return {
    ...base,
    reason: 'Demande pour dossier employeur',
    fields: [
      { name: 'academic_year', labelKey: 'admin.documentsModule.fields.academicYear', value: '2025-2026' },
      { name: 'purpose', labelKey: 'admin.documentsModule.fields.purpose', value: 'Stage été' },
    ],
    attachments: [
      { id: 'a1', name: 'piece_identite.pdf', type: 'SUPPORTING', uploadedAt: '2026-05-14T09:00:00' },
    ],
    workflowSteps: [
      { id: 'w1', code: 'submit', labelKey: 'admin.documentsModule.workflow.submit', status: 'completed', performedAt: '2026-05-14T10:00:00', performedBy: base.student.fullName },
      { id: 'w2', code: 'verify', labelKey: 'admin.documentsModule.workflow.verify', status: 'in_progress' },
      { id: 'w3', code: 'reserve', labelKey: 'admin.documentsModule.workflow.reserve', status: 'pending' },
      { id: 'w4', code: 'generate', labelKey: 'admin.documentsModule.workflow.generate', status: 'pending' },
      { id: 'w5', code: 'deliver', labelKey: 'admin.documentsModule.workflow.deliver', status: 'pending' },
    ],
    reservation: base.hasReservation
      ? {
          id: 'res-1',
          resourceName: 'Guichet Scolarité A',
          resourceType: 'counter',
          startAt: '2026-05-20T14:00:00',
          endAt: '2026-05-20T14:30:00',
          status: 'approved',
          location: 'Bâtiment A — RDC',
        }
      : undefined,
    validationHistory: [
      { at: '2026-05-14T10:05:00', by: 'Système', action: 'submitted' },
      { at: '2026-05-15T09:12:00', by: 'Agent Scolarité', action: 'under_verification', note: 'Vérification SRF en cours' },
    ],
    generatedOutputs: base.autoGenerated
      ? [{ id: 'o1', format: 'PDF', generatedAt: '2026-05-16T11:00:00', signed: false }]
      : [],
    insights: base.student.srfClearance
      ? ['admin.documentsModule.insights.srfClear']
      : ['admin.documentsModule.insights.srfBlocked'],
  };
}

export const MOCK_DASHBOARD: DocumentsDashboardData = {
  summary: {
    activeRequests: 47,
    pendingApprovals: 12,
    slaAtRisk: 5,
    reservationsToday: 18,
    autoGeneratedWeek: 34,
    rejectionRate: 8.2,
    avgProcessingHours: 36.5,
  },
  statusDistribution: [
    { status: 'submitted', count: 8 },
    { status: 'under_verification', count: 14 },
    { status: 'waiting_reservation', count: 6 },
    { status: 'ready', count: 9 },
    { status: 'delivered', count: 22 },
    { status: 'rejected', count: 4 },
  ],
  serviceWorkload: [
    { service: 'Scolarité', load: 18, capacity: 24 },
    { service: 'Stages', load: 12, capacity: 16 },
    { service: 'Finances', load: 9, capacity: 12 },
    { service: 'Archives', load: 6, capacity: 8 },
  ],
  slaTrend: [
    { day: 'Lun', onTime: 12, breached: 1 },
    { day: 'Mar', onTime: 15, breached: 2 },
    { day: 'Mer', onTime: 11, breached: 0 },
    { day: 'Jeu', onTime: 14, breached: 3 },
    { day: 'Ven', onTime: 10, breached: 1 },
  ],
  reservationOccupancy: [
    { hour: '09:00', percent: 45 },
    { hour: '10:00', percent: 72 },
    { hour: '11:00', percent: 88 },
    { hour: '14:00', percent: 65 },
    { hour: '15:00', percent: 54 },
    { hour: '16:00', percent: 38 },
  ],
  rejectionCauses: [
    { cause: 'missing_attachment', count: 12 },
    { cause: 'srf_unpaid', count: 8 },
    { cause: 'invalid_data', count: 5 },
    { cause: 'other', count: 3 },
  ],
  insights: [
    { id: 'i1', severity: 'warning', messageKey: 'admin.documentsModule.insights.overloadScolarite' },
    { id: 'i2', severity: 'critical', messageKey: 'admin.documentsModule.insights.slaRisk' },
    { id: 'i3', severity: 'info', messageKey: 'admin.documentsModule.insights.reservationPeak' },
  ],
  recentRequests: MOCK_REQUESTS.slice(0, 6),
};

export const MOCK_RESOURCES: AdministrativeResourceItem[] = [
  { id: 'r1', code: 'guichet-a', name: 'Guichet Scolarité A', resourceType: 'counter', location: 'Bât. A RDC', capacity: 1, isActive: true, occupancyPercent: 72 },
  { id: 'r2', code: 'guichet-b', name: 'Guichet Finances', resourceType: 'counter', location: 'Bât. B', capacity: 1, isActive: true, occupancyPercent: 55 },
  { id: 'r3', code: 'salle-signature', name: 'Salle signatures', resourceType: 'room', location: 'Bât. A 1er', capacity: 4, isActive: true, occupancyPercent: 40 },
  { id: 'r4', code: 'bureau-stages', name: 'Bureau stages', resourceType: 'office', location: 'Bât. C', capacity: 2, isActive: true, occupancyPercent: 85 },
];

export const MOCK_TEMPLATES: DocumentTemplateItem[] = [
  { id: 't1', code: 'att-scol-fr', name: 'Attestation scolarité FR', documentTypeCode: 'attestation-scolarite', language: 'fr', isDefault: true, isActive: true, placeholders: ['student_name', 'program', 'academic_year'] },
  { id: 't2', code: 'conv-stage-fr', name: 'Convention stage FR', documentTypeCode: 'convention-stage', language: 'fr', isDefault: true, isActive: true, placeholders: ['student_name', 'company', 'dates'] },
];

export const MOCK_WORKFLOWS: WorkflowDefinition[] = [
  {
    id: 'wf1',
    documentTypeCode: 'attestation-scolarite',
    isActive: true,
    steps: [
      { code: 'submit', labelKey: 'admin.documentsModule.workflow.submit' },
      { code: 'verify', labelKey: 'admin.documentsModule.workflow.verify', requiredRole: 'agent' },
      { code: 'generate', labelKey: 'admin.documentsModule.workflow.generate' },
      { code: 'deliver', labelKey: 'admin.documentsModule.workflow.deliver' },
    ],
  },
  {
    id: 'wf2',
    documentTypeCode: 'convention-stage',
    isActive: true,
    steps: [
      { code: 'submit', labelKey: 'admin.documentsModule.workflow.submit' },
      { code: 'verify', labelKey: 'admin.documentsModule.workflow.verify' },
      { code: 'reserve', labelKey: 'admin.documentsModule.workflow.reserve' },
      { code: 'sign', labelKey: 'admin.documentsModule.workflow.sign' },
      { code: 'deliver', labelKey: 'admin.documentsModule.workflow.deliver' },
    ],
  },
];

export const MOCK_SLA_RULES: SlaRuleItem[] = [
  { id: 'sla1', name: 'Attestation standard', documentTypeCode: 'attestation-scolarite', slaHours: 48, escalationHours: 36, autoAssign: true, reminderBeforeHours: 12, isActive: true },
  { id: 'sla2', name: 'Convention stage', documentTypeCode: 'convention-stage', slaHours: 72, escalationHours: 48, autoAssign: true, reminderBeforeHours: 24, isActive: true },
  { id: 'sla3', name: 'Urgence examens', slaHours: 24, escalationHours: 12, autoAssign: true, reminderBeforeHours: 6, isActive: true },
];

export const MOCK_ANALYTICS: DocumentsAnalyticsData = {
  processingTimes: [
    { service: 'Scolarité', avgHours: 28 },
    { service: 'Stages', avgHours: 52 },
    { service: 'Finances', avgHours: 18 },
    { service: 'Archives', avgHours: 96 },
  ],
  reservationSuccessRate: 94.2,
  autoGenerationRate: 67.5,
  bottlenecks: [
    { step: 'verify', avgHours: 18 },
    { step: 'reserve', avgHours: 24 },
    { step: 'sign', avgHours: 12 },
  ],
  workloadHeatmap: [
    { day: 'Mon', hour: 10, load: 8 },
    { day: 'Mon', hour: 14, load: 6 },
    { day: 'Tue', hour: 10, load: 12 },
    { day: 'Wed', hour: 11, load: 15 },
    { day: 'Thu', hour: 10, load: 10 },
    { day: 'Fri', hour: 9, load: 5 },
  ],
  deliveryAnalytics: [
    { method: 'digital', count: 145 },
    { method: 'pickup', count: 89 },
    { method: 'signature', count: 34 },
    { method: 'mail', count: 12 },
  ],
};

export function filterMockRequests(params?: {
  search?: string;
  status?: string;
  page?: number;
  page_size?: number;
}): PaginatedDocumentRequests {
  let items = [...MOCK_REQUESTS];
  if (params?.status) items = items.filter((r) => r.status === params.status);
  if (params?.search) {
    const q = params.search.toLowerCase();
    items = items.filter(
      (r) =>
        r.reference.toLowerCase().includes(q) ||
        r.student.fullName.toLowerCase().includes(q) ||
        r.documentTypeCode.includes(q),
    );
  }
  const page = params?.page ?? 1;
  const pageSize = params?.page_size ?? 15;
  const total = items.length;
  const start = (page - 1) * pageSize;
  return {
    items: items.slice(start, start + pageSize),
    page,
    page_size: pageSize,
    total,
    total_pages: Math.ceil(total / pageSize) || 1,
  };
}
