# Generated by Django 4.2.29 on 2026-05-19 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0009_compliance_and_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_et_roles', '0005_student_internship_derived_fields'),
        ('encadrant', '0002_erms_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='supervision_meetings/%Y/%m/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=16)),
                ('interval_count', models.PositiveSmallIntegerField(default=1)),
                ('until_date', models.DateField(blank=True, null=True)),
                ('occurrences_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('CONFIRMED', 'Confirmed'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed'), ('NEEDS_FOLLOWUP', 'Needs follow-up'), ('REMINDER_SENT', 'Reminder sent'), ('NOTE_ADDED', 'Note added'), ('NOTIFIED', 'Notification sent')], db_index=True, max_length=32)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-planned_start', '-scheduled_at']},
        ),
        migrations.RemoveIndex(
            model_name='meeting',
            name='encadrant_m_encadra_bc21db_idx',
        ),
        migrations.RemoveIndex(
            model_name='meeting',
            name='encadrant_m_workspa_d09a1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='meeting',
            name='encadrant_m_status_1b6fba_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='encadrant_r_status_8fa12e_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='encadrant_r_status_562fa9_idx',
            old_name='encadrant_r_status__8e0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='encadrant_r_severit_336f3b_idx',
            old_name='encadrant_r_severit_2a8c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='encadrant_r_filiere_8f6850_idx',
            old_name='encadrant_r_filiere_9c4e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='encadrant_r_is_over_1391b1_idx',
            old_name='encadrant_r_is_over_7f3b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='encadrant_r_report__498246_idx',
            old_name='encadrant_r_report__4d1e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='reportobligation',
            new_name='encadrant_r_encadra_19f90f_idx',
            old_name='encadrant_r_encadra_5d6e7f_idx',
        ),
        migrations.RenameIndex(
            model_name='reportobligation',
            new_name='encadrant_r_student_94e6fb_idx',
            old_name='encadrant_r_student_8g9h0i_idx',
        ),
        migrations.RenameIndex(
            model_name='reportworkflowevent',
            new_name='encadrant_r_report__134c06_idx',
            old_name='encadrant_r_report__1a2b3c_idx',
        ),
        migrations.AddField(
            model_name='meeting',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_meetings', to='admin_management.academiclevel'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='academic_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_meetings', to='admin_management.academicsector'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_meetings', to='admin_management.academicyear'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_meetings', to='admin_management.assignment'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_meetings', to='admin_management.classgroup'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supervision_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_meetings', to='admin_management.filiere'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='follow_up_actions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='internship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervision_meetings', to='admin_management.internshiptype'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_recurring',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_mode',
            field=models.CharField(choices=[('IN_PERSON', 'In person'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], db_index=True, default='IN_PERSON', max_length=16),
        ),
        migrations.AddField(
            model_name='meeting',
            name='next_suggested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='planned_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='planned_start',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=16),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='student_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervision_meetings', to='accounts_et_roles.studentprofile'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('FOLLOW_UP', 'Follow-up Meeting'), ('INTERNSHIP_COACHING', 'Internship Coaching'), ('PROGRESS_REVIEW', 'Progress Review'), ('MID_TERM_EVAL', 'Mid-term Evaluation'), ('FINAL_EVAL', 'Final Evaluation'), ('PROBLEM_RESOLUTION', 'Problem Resolution'), ('EMERGENCY', 'Emergency Meeting'), ('ORIENTATION', 'Orientation Meeting'), ('ONLINE', 'Online Meeting'), ('COMPANY_FOLLOWUP', 'Company Follow-up'), ('ONE_ON_ONE', 'One-on-one (legacy)'), ('GROUP', 'Group (legacy)'), ('JURY', 'Jury session (legacy)'), ('REVIEW', 'Review (legacy)'), ('MILESTONE', 'Milestone (legacy)')], db_index=True, default='FOLLOW_UP', max_length=24),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed'), ('NEEDS_FOLLOWUP', 'Needs Follow-up'), ('NO_SHOW', 'No-show (legacy)')], db_index=True, default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportworkflowevent',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED', 'Submitted'), ('RESUBMITTED', 'Resubmitted'), ('ASSIGNED_REVIEWER', 'Reviewer assigned'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REQUESTED_CHANGES', 'Changes requested'), ('ESCALATED', 'Escalated'), ('ARCHIVED', 'Archived'), ('NOTE_ADDED', 'Note added'), ('NOTIFIED', 'Notification sent'), ('PRIORITY_RECALCULATED', 'Priority recalculated')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['encadrant_profile', '-planned_start'], name='encadrant_m_encadra_63cbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['student_profile', '-planned_start'], name='encadrant_m_student_9624ed_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['workspace', '-planned_start'], name='encadrant_m_workspa_e82482_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', '-planned_start'], name='encadrant_m_status_49815c_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_type', 'status'], name='encadrant_m_meeting_83ec85_idx'),
        ),
        migrations.AddField(
            model_name='meetingtimelineevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingtimelineevent',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='encadrant.meeting'),
        ),
        migrations.AddField(
            model_name='meetingrecurrence',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence', to='encadrant.meeting'),
        ),
        migrations.AddField(
            model_name='meetingattachment',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='encadrant.meeting'),
        ),
        migrations.AddField(
            model_name='meetingattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='meetingtimelineevent',
            index=models.Index(fields=['meeting', 'created_at'], name='encadrant_m_meeting_1b8635_idx'),
        ),
    ]
