# Generated by Django 4.2.30 on 2026-09-02 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0016_filiere_specialization_domains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_et_roles', '0006_student_internship_status_fields'),
        ('encadrant', '0004_meeting_jitsi_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='workspace_documents/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('report', 'Report'), ('research', 'Research'), ('internship', 'Internship'), ('meeting', 'Meeting'), ('shared', 'Shared')], db_index=True, default='shared', max_length=16)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('viewed_by_encadrant_at', models.DateTimeField(blank=True, null=True)),
                ('encadrant_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_documents', to='admin_management.encadrantprofile')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_documents', to='accounts_et_roles.studentprofile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkspaceDocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('grade', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In review'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=16)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='encadrant.workspacedocument')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='workspacedocument',
            index=models.Index(fields=['student_profile', '-created_at'], name='encadrant_w_student_925380_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacedocument',
            index=models.Index(fields=['encadrant_profile', '-created_at'], name='encadrant_w_encadra_649900_idx'),
        ),
    ]
