# Generated by Django 4.2.29 on 2026-05-19 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0009_compliance_and_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stage', '0001_initial'),
        ('accounts_et_roles', '0005_student_internship_derived_fields'),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementInternshipDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internship_type_code', models.CharField(blank=True, default='', max_length=64)),
                ('duration', models.CharField(blank=True, default='', max_length=128)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('work_mode', models.CharField(choices=[('ON_SITE', 'On-site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], default='ON_SITE', max_length=16)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('recruiter_name', models.CharField(blank=True, default='', max_length=255)),
                ('recruiter_email', models.EmailField(blank=True, default='', max_length=254)),
                ('company_sector', models.CharField(blank=True, default='', max_length=128)),
                ('internship_start_date', models.DateField(blank=True, null=True)),
                ('internship_end_date', models.DateField(blank=True, null=True)),
                ('compensation', models.CharField(blank=True, default='', max_length=255)),
                ('offer_status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSING_SOON', 'Closing soon'), ('CLOSED', 'Closed'), ('FILLED', 'Filled')], db_index=True, default='OPEN', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnnouncementPublicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived'), ('EXPIRED', 'Expired'), ('HIDDEN', 'Hidden'), ('DUPLICATED', 'Duplicated')], db_index=True, max_length=16)),
                ('previous_status', models.CharField(blank=True, default='', max_length=16)),
                ('new_status', models.CharField(blank=True, default='', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnnouncementBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookmark_type', models.CharField(choices=[('SAVE', 'Saved'), ('FOLLOW', 'Following')], default='SAVE', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='announcementattachment',
            options={'ordering': ['sort_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='announcementtype',
            options={'ordering': ['sort_order', 'code']},
        ),
        migrations.RemoveIndex(
            model_name='announcementofferlink',
            name='announcemen_offer_i_18f902_idx',
        ),
        migrations.AddField(
            model_name='announcement',
            name='application_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='announcement',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/covers/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='dismiss_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='external_link',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='announcement',
            name='overrides_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='overrides_mute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='publish_end_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='publish_start_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='recommendation_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='announcement',
            name='save_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_scope',
            field=models.CharField(choices=[('ALL_STUDENTS', 'All students'), ('TARGETED', 'Targeted audience'), ('CUSTOM', 'Custom rules')], db_index=True, default='ALL_STUDENTS', max_length=32),
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='visibility_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='announcementattachment',
            name='external_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='announcementattachment',
            name='kind',
            field=models.CharField(choices=[('FILE', 'File'), ('IMAGE', 'Image'), ('PDF', 'PDF'), ('DOCUMENT', 'Document'), ('EXTERNAL_LINK', 'External link')], default='FILE', max_length=16),
        ),
        migrations.AddField(
            model_name='announcementattachment',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='announcementattachment',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcementtarget',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_targets', to='admin_management.academiclevel'),
        ),
        migrations.AddField(
            model_name='announcementtarget',
            name='academic_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_targets', to='admin_management.academicsector'),
        ),
        migrations.AddField(
            model_name='announcementtarget',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_targets', to='admin_management.academicyear'),
        ),
        migrations.AddField(
            model_name='announcementtarget',
            name='internship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_targets', to='admin_management.internshiptype'),
        ),
        migrations.AddField(
            model_name='announcementtype',
            name='is_bannable',
            field=models.BooleanField(default=True, help_text='Students can ban this type when True.'),
        ),
        migrations.AddField(
            model_name='announcementtype',
            name='is_internship_related',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='announcementtype',
            name='is_mutable',
            field=models.BooleanField(default=True, help_text='Students can mute this type when True.'),
        ),
        migrations.AddField(
            model_name='announcementtype',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='announcementtype',
            name='recommendation_boost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='announcementtype',
            name='recommendation_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='announcementtype',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcementtype',
            name='stage_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_types', to='admin_management.internshiptype'),
        ),
        migrations.AddField(
            model_name='studentannouncementpreference',
            name='is_banned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='studentannouncementpreference',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent'), ('PINNED', 'Pinned'), ('INSTITUTIONAL_CRITICAL', 'Institutional Critical')], db_index=True, default='NORMAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived'), ('HIDDEN', 'Hidden')], db_index=True, default='DRAFT', max_length=16),
        ),
        migrations.AlterField(
            model_name='announcementattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='announcements/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='announcementtarget',
            name='target_type',
            field=models.CharField(choices=[('ALL', 'All users'), ('FILIERE', 'Program / Filière'), ('CLASS_GROUP', 'Class group'), ('ACADEMIC_LEVEL', 'Academic level'), ('ACADEMIC_YEAR', 'Academic year'), ('ACADEMIC_SECTOR', 'Specialization / sector'), ('INTERNSHIP_TYPE', 'Internship type'), ('INTERNSHIP_SEEKING', 'Students seeking internship'), ('ROLE', 'Role'), ('USER', 'Specific user'), ('LEVEL', 'Education level (legacy)'), ('CUSTOM', 'Custom')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='announcementtype',
            name='default_priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent'), ('PINNED', 'Pinned'), ('INSTITUTIONAL_CRITICAL', 'Institutional Critical')], default='NORMAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='recommendationscore',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='studentannouncementaction',
            name='action_type',
            field=models.CharField(choices=[('VIEW', 'View'), ('CLICK', 'Click'), ('SAVE', 'Save'), ('DISMISS', 'Dismiss'), ('SHARE', 'Share'), ('FOLLOW', 'Follow'), ('UNFOLLOW', 'Unfollow'), ('READ_TIME', 'Read time')], db_index=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['priority', 'status'], name='announcemen_priorit_9a8f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['publish_start_at', 'publish_end_at'], name='announcemen_publish_fa4ec8_idx'),
        ),
        migrations.AddField(
            model_name='studentannouncementbookmark',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='studentannouncementbookmark',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_bookmarks', to='accounts_et_roles.studentprofile'),
        ),
        migrations.AddField(
            model_name='announcementpublicationlog',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_logs', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='announcementpublicationlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcementinternshipdetails',
            name='announcement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internship_details', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='announcementinternshipdetails',
            name='internship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_internships', to='admin_management.internshiptype'),
        ),
        migrations.AddField(
            model_name='announcementinternshipdetails',
            name='linked_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_internship_details', to='stage.internshipoffer'),
        ),
        migrations.AddConstraint(
            model_name='studentannouncementbookmark',
            constraint=models.UniqueConstraint(fields=('student_profile', 'announcement', 'bookmark_type'), name='uniq_student_announcement_bookmark'),
        ),
    ]
