# Generated by Django 4.2.30 on 2026-06-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_sync_engagement_counters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementpublicationlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SCHEDULED', 'Scheduled'), ('SCHEDULE_MODIFIED', 'Schedule modified'), ('SCHEDULE_CANCELLED', 'Schedule cancelled'), ('PUBLISHED', 'Published'), ('AUTO_PUBLISHED', 'Auto published'), ('UNPUBLISHED', 'Unpublished'), ('ARCHIVED', 'Archived'), ('UNARCHIVED', 'Unarchived'), ('EXPIRED', 'Expired'), ('HIDDEN', 'Hidden'), ('DUPLICATED', 'Duplicated')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentannouncementbookmark',
            name='bookmark_type',
            field=models.CharField(choices=[('SAVE', 'Saved'), ('FAVORITE', 'Favorite'), ('FOLLOW', 'Following')], default='SAVE', max_length=16),
        ),
    ]
