export { default as ChatMessageBubbleContent } from './components/ChatMessageBubbleContent';
export type { ChatMessageBubbleContentProps } from './components/ChatMessageBubbleContent';
export { default as ContextualChatShell } from './components/ContextualChatShell';
export type { ContextualChatShellProps } from './components/ContextualChatShell';
export { useContextualChat } from './hooks/useContextualChat';
export type { ChatModule, SmartActionCode, ConversationDto } from './types';
export { ChatUnreadProvider, useChatUnread, useChatUnreadCount } from './context/ChatUnreadContext';
export { default as NavChatUnreadBadge } from './components/NavChatUnreadBadge';
export { ADMIN_NAV_CHAT_MODULES, ADMIN_NAV_CHAT_SCOPES, ENCADRANT_PORTAL_CHAT_SCOPE, STUDENT_NAV_CHAT_MODULES, STUDENT_NAV_CHAT_SCOPES, resolveChatNavUnread, scopeUnreadKey } from './config/chatNavModuleMap';
export type { ChatNavUnreadScope } from './config/chatNavModuleMap';
export { default as ChatComposerTagPicker } from './components/ChatComposerTagPicker';
export { default as ChatComposerEntityPicker } from './components/ChatComposerEntityPicker';
export { default as ChatComposerModuleExtras } from './components/ChatComposerModuleExtras';
export { default as ChatMessageEntityRefs } from './components/ChatMessageEntityRefs';
export { useChatEntityReferences, clearChatEntityReferencesCache } from './hooks/useChatEntityReferences';
export { useChatComposerEntityState } from './hooks/useChatComposerEntityState';
export type { ChatEntityReference, ChatComposerPendingEntity } from './types/chatEntityTypes';
export { default as ChatMessageTags } from './components/ChatMessageTags';
export { useAuthorizedChatTags, clearChatTagsCache } from './hooks/useAuthorizedChatTags';
export { useChatComposerTagState } from './hooks/useChatComposerTagState';
export { useSupportChatAreaComposer } from './hooks/useSupportChatAreaComposer';
export type { ChatTagOption, ChatComposerPendingTag } from './types/chatTagTypes';
export * from './api/chatApi';
