# Generated by Django 4.2.29 on 2026-05-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documenttype_service_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='service_config_json',
            field=models.JSONField(blank=True, default=dict, help_text='Full service catalog configuration (availability, delivery, workflow, etc.).'),
        ),
    ]
