import { FunctionComponent } from 'react';
import { useTranslation } from 'react-i18next';
import { Download, Mail, PenLine, CalendarCheck, Store, Sparkles, Send, Layers, FileType2, FileText } from 'lucide-react';

import type { DocumentServiceConfig } from '../../types/documentServiceCatalog';
import ServiceCatalogTemplateUpload from './ServiceCatalogTemplateUpload';

interface ToggleCardProps {
  id: string;
  icon: typeof Download;
  label: string;
  description?: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
  disabled?: boolean;
}

export const ServiceCatalogToggleCard: FunctionComponent<ToggleCardProps> = ({
  id,
  icon: Icon,
  label,
  description,
  checked,
  onChange,
  disabled = false,
}) => (
  <button
    type="button"
    id={id}
    className={`admin-doc-studio-toggle-card ${checked ? 'is-selected' : ''} ${disabled ? 'is-disabled' : ''}`}
    onClick={() => !disabled && onChange(!checked)}
    aria-pressed={checked}
    disabled={disabled}
  >
    <span className="admin-doc-studio-toggle-card__icon" aria-hidden>
      <Icon className="h-5 w-5" />
    </span>
    <span className="admin-doc-studio-toggle-card__content">
      <span className="admin-doc-studio-toggle-card__label">{label}</span>
      {description && <span className="admin-doc-studio-toggle-card__desc">{description}</span>}
    </span>
    <span className={`admin-doc-studio-toggle-card__switch ${checked ? 'is-on' : ''}`} aria-hidden />
  </button>
);

interface RequestModeProps {
  onlineRequestEnabled: boolean;
  autoGenerateEnabled: boolean;
  serviceId?: string;
  template?: DocumentServiceConfig['template'];
  onOnlineChange: (v: boolean) => void;
  onAutoGenerateChange: (v: boolean) => void;
  onTemplateChange: (template: NonNullable<DocumentServiceConfig['template']>) => void;
  onPendingTemplateFileChange?: (file: File | null) => void;
}

export const ServiceCatalogRequestModeCards: FunctionComponent<RequestModeProps> = ({
  onlineRequestEnabled,
  autoGenerateEnabled,
  serviceId,
  template,
  onOnlineChange,
  onAutoGenerateChange,
  onTemplateChange,
  onPendingTemplateFileChange,
}) => {
  const { t } = useTranslation();
  const P = 'admin.documentsModule.catalog.form.studio.requestMode';
  const sections = 'admin.documentsModule.catalog.form.sections';

  return (
    <div className="admin-doc-studio-toggle-cards">
      <ServiceCatalogToggleCard
        id="req-online"
        icon={Send}
        label={t(`${P}.onlineRequest`)}
        description={t(`${P}.onlineRequestDesc`)}
        checked={onlineRequestEnabled}
        onChange={onOnlineChange}
      />
      <ServiceCatalogToggleCard
        id="req-auto"
        icon={Sparkles}
        label={t(`${P}.autoGenerate`)}
        description={t(`${P}.autoGenerateDesc`)}
        checked={autoGenerateEnabled}
        onChange={onAutoGenerateChange}
      />
      {autoGenerateEnabled && (
        <div className="admin-doc-studio-request-mode__template">
          <header className="admin-doc-studio-template__head">
            <div className="admin-doc-studio-template__head-main">
              <span className="admin-doc-studio-template__head-icon" aria-hidden>
                <Layers className="h-5 w-5" />
              </span>
              <div className="admin-doc-studio-template__head-copy">
                <h4 className="admin-doc-studio-template__head-title">
                  {t(`${sections}.template`)}
                </h4>
                <p className="admin-doc-studio-template__head-desc">
                  {t(`${sections}.templateHint`)}
                </p>
              </div>
            </div>
            <div className="admin-doc-studio-template__head-tags" aria-label={t(`${P}.formatsLabel`)}>
              <span className="admin-doc-studio-template__format-tag">
                <FileType2 className="h-3.5 w-3.5" aria-hidden />
                PDF
              </span>
              <span className="admin-doc-studio-template__format-tag">
                <FileText className="h-3.5 w-3.5" aria-hidden />
                DOCX
              </span>
            </div>
          </header>
          <ServiceCatalogTemplateUpload
            template={template}
            serviceId={serviceId}
            onChange={onTemplateChange}
            onPendingFileChange={onPendingTemplateFileChange}
          />
        </div>
      )}
    </div>
  );
};

interface DeliveryProps {
  onlineEnabled: boolean;
  downloadablePdf: boolean;
  emailDelivery: boolean;
  physicalEnabled: boolean;
  reservationRequired: boolean;
  signatureRequired: boolean;
  onOnlineEnabled: (v: boolean) => void;
  onDownloadablePdf: (v: boolean) => void;
  onEmailDelivery: (v: boolean) => void;
  onPhysicalEnabled: (v: boolean) => void;
  onReservationRequired: (v: boolean) => void;
  onSignatureRequired: (v: boolean) => void;
}

export const ServiceCatalogDeliveryCards: FunctionComponent<DeliveryProps> = ({
  onlineEnabled,
  downloadablePdf,
  emailDelivery,
  physicalEnabled,
  reservationRequired,
  signatureRequired,
  onOnlineEnabled,
  onDownloadablePdf,
  onEmailDelivery,
  onPhysicalEnabled,
  onReservationRequired,
  onSignatureRequired,
}) => {
  const { t } = useTranslation();
  const P = 'admin.documentsModule.catalog.form.studio.delivery';

  return (
    <div className="admin-doc-studio-delivery">
      <div className="admin-doc-studio-delivery__group">
        <h4 className="admin-doc-studio-delivery__group-title">{t(`${P}.onlineTitle`)}</h4>
        <div className="admin-doc-studio-toggle-cards">
          <ServiceCatalogToggleCard
            id="del-online"
            icon={Download}
            label={t('admin.documentsModule.catalog.form.toggles.onlineEnabled')}
            description={t(`${P}.onlineDesc`)}
            checked={onlineEnabled}
            onChange={onOnlineEnabled}
          />
          {onlineEnabled && (
            <>
              <ServiceCatalogToggleCard
                id="del-pdf"
                icon={Download}
                label={t('admin.documentsModule.catalog.form.toggles.downloadPdf')}
                checked={downloadablePdf}
                onChange={onDownloadablePdf}
              />
              <ServiceCatalogToggleCard
                id="del-email"
                icon={Mail}
                label={t('admin.documentsModule.catalog.form.toggles.emailDelivery')}
                checked={emailDelivery}
                onChange={onEmailDelivery}
              />
            </>
          )}
        </div>
      </div>

      <div className="admin-doc-studio-delivery__group">
        <h4 className="admin-doc-studio-delivery__group-title">{t(`${P}.physicalTitle`)}</h4>
        <div className="admin-doc-studio-toggle-cards">
          <ServiceCatalogToggleCard
            id="del-physical"
            icon={Store}
            label={t('admin.documentsModule.catalog.form.toggles.physicalEnabled')}
            description={t(`${P}.physicalDesc`)}
            checked={physicalEnabled}
            onChange={onPhysicalEnabled}
          />
          {physicalEnabled && (
            <>
              <ServiceCatalogToggleCard
                id="del-reserve"
                icon={CalendarCheck}
                label={t('admin.documentsModule.catalog.form.toggles.reservationRequired')}
                checked={reservationRequired}
                onChange={onReservationRequired}
              />
              <ServiceCatalogToggleCard
                id="del-sign"
                icon={PenLine}
                label={t('admin.documentsModule.catalog.form.toggles.signatureRequired')}
                checked={signatureRequired}
                onChange={onSignatureRequired}
              />
            </>
          )}
        </div>
      </div>
    </div>
  );
};
