/** Tokens UI — module Internship Offers (design system admin). */
export {
  STUDENT_SURFACE_CARD,
  STUDENT_SURFACE_CARD_INTERACTIVE,
  STUDENT_PRIMARY_BUTTON,
  STUDENT_SECTION_LINK,
  STUDENT_BACK_LINK as INTERNSHIP_OFFERS_BACK_LINK,
  STUDENT_EMPTY_STATE,
  STUDENT_TEXT_PRIMARY,
  STUDENT_TEXT_SECONDARY,
  STUDENT_TEXT_MUTED,
} from '../../design-system/studentTokens';
