# Generated by Django 4.2.29 on 2026-05-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversationcontext_messagereaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationcontext',
            options={},
        ),
        migrations.RenameIndex(
            model_name='conversationcontext',
            new_name='chat_conver_module_977739_idx',
            old_name='chat_conver_module_8f3c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationcontext',
            new_name='chat_conver_module_4c05f6_idx',
            old_name='chat_conver_module_9a1b4c_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationcontext',
            new_name='chat_conver_urgency_78e482_idx',
            old_name='chat_conver_urgency_2d8e1f_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereaction',
            new_name='chat_messag_message_a81d94_idx',
            old_name='chat_messag_message_4e7a9b_idx',
        ),
        migrations.AlterField(
            model_name='conversationcontext',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
