# Generated by Django 4.2.29 on 2026-06-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messageread_conversationcontext_extended'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messageread',
            new_name='chat_messag_user_id_b47113_idx',
            old_name='chat_messag_user_id_6f1a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='messageread',
            new_name='chat_messag_message_72c1ef_idx',
            old_name='chat_messag_message_8c3d4e_idx',
        ),
    ]
