# Generated by Django 4.2.29 on 2026-05-19 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_et_roles', '0005_student_internship_derived_fields'),
        ('admin_management', '0009_compliance_and_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('INSTALLMENT_OVERDUE', 'Installment overdue'), ('EXAM_RESTRICTION', 'Exam restriction warning'), ('CONVENTION_BLOCKED', 'Convention blocked'), ('PAYMENT_REJECTED', 'Payment rejected'), ('AT_RISK', 'Financial at risk'), ('GENERAL', 'General')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.PositiveSmallIntegerField(db_index=True)),
                ('label', models.CharField(help_text='e.g. tranche_1', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MAD', max_length=8)),
                ('due_date', models.DateField(db_index=True)),
                ('semester', models.PositiveSmallIntegerField(default=1, help_text='Semester this installment covers (1 or 2).')),
                ('academic_year', models.CharField(db_index=True, max_length=16)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING_VALIDATION', 'Pending validation'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], db_index=True, default='UNPAID', max_length=24)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_receipt', models.FileField(blank=True, null=True, upload_to='srf/installment_receipts/%Y/%m/')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['account', 'installment_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentProofSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MAD', max_length=8)),
                ('reference_number', models.CharField(blank=True, default='', max_length=128)),
                ('proof_file', models.FileField(upload_to='srf/payment_proofs/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REQUIRES_CORRECTION', 'Requires correction')], db_index=True, default='PENDING', max_length=24)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramExamPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('exam_start', models.DateField(db_index=True)),
                ('exam_end', models.DateField(db_index=True)),
                ('payment_deadline', models.DateField(blank=True, help_text='Last date to be financially clear before exams.', null=True)),
                ('warning_days_before', models.PositiveSmallIntegerField(default=14, help_text='Days before exam_start to start AT_RISK warnings.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-exam_start'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_take_exams', models.BooleanField(db_index=True, default=False)),
                ('can_download_convention', models.BooleanField(db_index=True, default=False)),
                ('internship_eligible', models.BooleanField(db_index=True, default=False)),
                ('financial_clearance', models.BooleanField(db_index=True, default=False)),
                ('blocking_reasons', models.JSONField(blank=True, default=list)),
                ('required_semester', models.PositiveSmallIntegerField(default=1)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Student academic access records',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='current_academic_year',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='financial_status',
            field=models.CharField(choices=[('CLEAR', 'Clear'), ('PARTIAL', 'Partial'), ('OVERDUE', 'Overdue'), ('BLOCKED', 'Blocked'), ('AT_RISK', 'At risk'), ('PENDING_VALIDATION', 'Pending validation')], db_index=True, default='PENDING_VALIDATION', max_length=24),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='payment_plan_type',
            field=models.CharField(choices=[('FULL', 'Full payment'), ('INSTALLMENTS', 'Installments / tranches')], db_index=True, default='FULL', max_length=16),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['financial_status', 'payment_plan_type'], name='srf_financi_financi_62683a_idx'),
        ),
        migrations.AddField(
            model_name='studentacademicaccess',
            name='student_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_access', to='accounts_et_roles.studentprofile'),
        ),
        migrations.AddField(
            model_name='programexamperiod',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_periods', to='admin_management.academicyear'),
        ),
        migrations.AddField(
            model_name='programexamperiod',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_periods', to='admin_management.filiere'),
        ),
        migrations.AddField(
            model_name='paymentproofsubmission',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='srf.financialaccount'),
        ),
        migrations.AddField(
            model_name='paymentproofsubmission',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proof_submissions', to='srf.installment'),
        ),
        migrations.AddField(
            model_name='paymentproofsubmission',
            name='linked_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proof_submissions', to='srf.payment'),
        ),
        migrations.AddField(
            model_name='paymentproofsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentproofsubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_payment_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='srf.financialaccount'),
        ),
        migrations.AddField(
            model_name='installment',
            name='linked_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='srf.payment'),
        ),
        migrations.AddField(
            model_name='installment',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_installments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialriskalert',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='srf.financialaccount'),
        ),
        migrations.AddField(
            model_name='financialriskalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_financial_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialriskalert',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_risk_alerts', to='accounts_et_roles.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='programexamperiod',
            constraint=models.UniqueConstraint(fields=('filiere', 'academic_year', 'semester'), name='uniq_exam_period_program_semester'),
        ),
        migrations.AddIndex(
            model_name='paymentproofsubmission',
            index=models.Index(fields=['status', '-created_at'], name='srf_payment_status_58249e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentproofsubmission',
            index=models.Index(fields=['account', 'status'], name='srf_payment_account_be4099_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['payment_status', 'due_date'], name='srf_install_payment_bd89e5_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['academic_year', 'semester', 'payment_status'], name='srf_install_academi_890401_idx'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('account', 'installment_number', 'academic_year'), name='uniq_installment_per_account_year'),
        ),
        migrations.AddIndex(
            model_name='financialriskalert',
            index=models.Index(fields=['is_resolved', 'severity'], name='srf_financi_is_reso_6c47cb_idx'),
        ),
        migrations.AddIndex(
            model_name='financialriskalert',
            index=models.Index(fields=['student_profile', 'is_resolved'], name='srf_financi_student_6db592_idx'),
        ),
    ]
