# Generated by Django 4.2.29 on 2026-05-19 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srf', '0002_compliance_and_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('MAPPING', 'Mapping'), ('VALIDATING', 'Validating'), ('PREVIEW_READY', 'Preview ready'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled back'), ('CANCELLED', 'Cancelled')], db_index=True, default='UPLOADED', max_length=24)),
                ('import_mode', models.CharField(choices=[('CREATE_ONLY', 'Create only'), ('UPDATE', 'Update existing'), ('MERGE', 'Merge'), ('DRY_RUN', 'Dry run / test')], db_index=True, default='MERGE', max_length=16)),
                ('file_format', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel'), ('JSON', 'JSON'), ('OTHER', 'Other')], default='CSV', max_length=8)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('stored_file', models.FileField(blank=True, null=True, upload_to='srf/imports/inbox/%Y/%m/')),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('file_checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('academic_year', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('warning_rows', models.PositiveIntegerField(default=0)),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('affected_students', models.PositiveIntegerField(default=0)),
                ('column_mapping_json', models.JSONField(blank=True, default=dict)),
                ('preview_json', models.JSONField(blank=True, default=dict)),
                ('validation_json', models.JSONField(blank=True, default=dict)),
                ('errors_json', models.JSONField(blank=True, default=list)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('parent_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='srf.financialimportbatch')),
                ('rolled_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srf_import_rollbacks', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srf_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialImportMappingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('source_system', models.CharField(blank=True, default='', help_text='e.g. sage, sap, custom_erp', max_length=64)),
                ('column_mapping_json', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srf_import_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialImportAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOAD', 'Upload'), ('VALIDATE', 'Validate'), ('PREVIEW', 'Preview'), ('EXECUTE', 'Execute'), ('PROGRESS', 'Progress'), ('COMPLETE', 'Complete'), ('FAIL', 'Fail'), ('ROLLBACK', 'Rollback'), ('RETRY', 'Retry'), ('DELETE_FILE', 'Delete file'), ('SECURITY_REJECT', 'Security reject')], db_index=True, max_length=24)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('message', models.TextField(blank=True, default='')),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='srf.financialimportbatch')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialImportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_profile_id', models.PositiveIntegerField(db_index=True)),
                ('before_state_json', models.JSONField(default=dict)),
                ('after_state_json', models.JSONField(blank=True, default=dict)),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('applied', models.BooleanField(default=False)),
                ('rolled_back', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_snapshots', to='srf.financialaccount')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='srf.financialimportbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'applied'], name='srf_financi_batch_i_139557_idx'), models.Index(fields=['account', 'batch'], name='srf_financi_account_f1dc78_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='financialimportbatch',
            index=models.Index(fields=['status', '-created_at'], name='srf_financi_status_6d32ee_idx'),
        ),
        migrations.AddIndex(
            model_name='financialimportbatch',
            index=models.Index(fields=['started_by', '-created_at'], name='srf_financi_started_87138b_idx'),
        ),
        migrations.AddIndex(
            model_name='financialimportauditevent',
            index=models.Index(fields=['batch', 'created_at'], name='srf_financi_batch_i_52d456_idx'),
        ),
    ]
