# Generated by Django 4.2.29 on 2026-05-19 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0009_compliance_and_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srf', '0003_financial_import_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='SrfNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-app'), ('BOTH', 'Email and in-app')], default='BOTH', max_length=16)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=16)),
                ('subject_template', models.CharField(blank=True, default='', max_length=255)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SrfRestrictionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.CharField(default='default', max_length=32, unique=True)),
                ('stop_reminders_on_payment', models.BooleanField(default=True)),
                ('mark_at_risk_on_warning', models.BooleanField(default=True)),
                ('escalate_unresolved_after_days', models.PositiveSmallIntegerField(default=14)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_in_app_notifications', models.BooleanField(default=True)),
                ('enable_critical_alerts', models.BooleanField(default=True)),
                ('unpaid_blocks_exams', models.BooleanField(default=True)),
                ('unpaid_blocks_convention', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'SRF restriction policy',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SrfWarningTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('label', models.CharField(max_length=128)),
                ('days_before_exam_start', models.PositiveSmallIntegerField(help_text='Activate this tier when exams are within N days.')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('reminder_interval_days', models.PositiveSmallIntegerField(default=7)),
                ('max_reminders', models.PositiveSmallIntegerField(blank=True, help_text='Leave empty for unlimited reminders in this tier.', null=True)),
                ('cooldown_hours', models.PositiveSmallIntegerField(default=0)),
                ('block_convention', models.BooleanField(default=False)),
                ('convention_block_days_before', models.PositiveSmallIntegerField(blank=True, help_text='Block convention N days before exam_start when set.', null=True)),
                ('block_exams', models.BooleanField(default=False, help_text='When true, exams are blocked at exam_start for non-clear students.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-days_before_exam_start', 'sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='programexamperiod',
            name='academic_level',
            field=models.ForeignKey(blank=True, help_text='Optional — when empty, applies to all levels in the program.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_periods', to='admin_management.academiclevel'),
        ),
        migrations.AddField(
            model_name='programexamperiod',
            name='convention_block_date',
            field=models.DateField(blank=True, help_text='Date from which internship conventions are blocked for unpaid students.', null=True),
        ),
        migrations.CreateModel(
            name='SrfConfigAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('message', models.TextField(blank=True, default='')),
                ('before_json', models.JSONField(blank=True, default=dict)),
                ('after_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srf_config_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', '-created_at'], name='srf_srfconf_entity__7e99cb_idx')],
            },
        ),
    ]
