# Generated by Django 4.2.29 on 2026-05-17 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0001_initial'),
        ('accounts_et_roles', '0002_studentprofile_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_year',
            field=models.CharField(blank=True, default='', help_text='Format: 2025-2026', max_length=16),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='admin_management.classgroup'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='admin_management.filiere'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_login_completed',
            field=models.BooleanField(db_index=True, default=False, help_text='True after the first successful SSO login and credential provisioning.'),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_access_granted',
            field=models.BooleanField(db_index=True, default=False, help_text='Admin-granted permission to use the platform (independent of SSO identity).'),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_access_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_access_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='sso_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Student may authenticate via school SSO (Auth0).'),
        ),
        migrations.AlterField(
            model_name='accountstatuslog',
            name='new_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived'), ('LOCKED', 'Locked')], max_length=16),
        ),
        migrations.AlterField(
            model_name='accountstatuslog',
            name='old_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived'), ('LOCKED', 'Locked')], max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived'), ('LOCKED', 'Locked')], db_index=True, default='PENDING', max_length=16),
        ),
    ]
