# Generated by Django 4.2.29 on 2026-05-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0003_esca_academic_hierarchy'),
        ('accounts_et_roles', '0003_studentprofile_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='admin_management.academiclevel'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='admin_management.academicsector'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_year_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='admin_management.academicyear'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='internship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='admin_management.internshiptype'),
        ),
    ]
